/* ───────────────────────────────────────────────────
   Pattern Drift — Game Data
   All 224 topics from 8 collections, 2 domains
   ─────────────────────────────────────────────────── */

const DOMAINS = {
  ml:      { label: 'Machine Learning', color: '#4fc3f7', glow: 'rgba(79,195,247,' },
  markets: { label: 'Markets',          color: '#81c784', glow: 'rgba(129,199,132,' }
};

const COLLECTIONS = {
  'stats':        { domain: 'ml',      label: 'Statistics' },
  'ml-math':      { domain: 'ml',      label: 'ML & Math' },
  'llm':          { domain: 'ml',      label: 'LLM' },
  'charts':       { domain: 'markets', label: 'Chart Patterns' },
  'indicators':   { domain: 'markets', label: 'Indicators' },
  'psychology':   { domain: 'markets', label: 'Psychology' },
  'mlops':        { domain: 'ml',      label: 'MLOps' },
  'risk':         { domain: 'markets', label: 'Risk & Portfolio' }
};

const GAME_TOPICS = [

  // ── Stats (34) ──────────────────────────────────
  { id:'mean-median', title:'Mean, Median & Mode', domain:'ml', col:'stats', cat:'Descriptive Stats', kw:['average','central tendency','median','mode','mean'] },
  { id:'variance-std', title:'Variance & Std Dev', domain:'ml', col:'stats', cat:'Descriptive Stats', kw:['spread','dispersion','standard deviation','variance','range'] },
  { id:'percentiles', title:'Percentiles & Quartiles', domain:'ml', col:'stats', cat:'Descriptive Stats', kw:['quartile','percentile','IQR','box plot','outlier'] },
  { id:'correlation', title:'Correlation', domain:'ml', col:'stats', cat:'Descriptive Stats', kw:['pearson','spearman','r-value','linear relationship','scatter plot'] },
  { id:'covariance', title:'Covariance', domain:'ml', col:'stats', cat:'Descriptive Stats', kw:['joint variability','covariance matrix','positive','negative'] },
  { id:'prob-basics', title:'Probability Basics', domain:'ml', col:'stats', cat:'Probability', kw:['event','sample space','union','intersection','complement','axioms'] },
  { id:'conditional', title:'Conditional Probability', domain:'ml', col:'stats', cat:'Probability', kw:['given','bayes','posterior','likelihood','prior','conditional'] },
  { id:'independence', title:'Independence', domain:'ml', col:'stats', cat:'Probability', kw:['independent events','joint probability','marginal','multiplication rule'] },
  { id:'combinatorics', title:'Combinatorics', domain:'ml', col:'stats', cat:'Probability', kw:['permutation','combination','factorial','counting','binomial coefficient'] },
  { id:'law-large-numbers', title:'Law of Large Numbers', domain:'ml', col:'stats', cat:'Probability', kw:['convergence','sample mean','expected value','weak law','strong law'] },
  { id:'normal', title:'Normal Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['gaussian','bell curve','z-score','standard normal','CLT'] },
  { id:'binomial', title:'Binomial Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['bernoulli','trials','success','failure','binary outcome'] },
  { id:'poisson', title:'Poisson Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['rare events','rate','lambda','count data','arrivals'] },
  { id:'exponential', title:'Exponential Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['waiting time','memoryless','decay','half-life','survival'] },
  { id:'uniform', title:'Uniform Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['equal probability','flat','rectangular','continuous','discrete'] },
  { id:'beta', title:'Beta Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['prior','proportion','bayesian','alpha','conjugate'] },
  { id:'chi-squared', title:'Chi-Squared Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['goodness of fit','degrees of freedom','test statistic','categorical'] },
  { id:'clt', title:'Central Limit Theorem', domain:'ml', col:'stats', cat:'Inference', kw:['sample mean','normal approximation','sampling distribution','standard error'] },
  { id:'confidence', title:'Confidence Intervals', domain:'ml', col:'stats', cat:'Inference', kw:['margin of error','interval estimate','z-interval','t-interval','coverage'] },
  { id:'hypothesis', title:'Hypothesis Testing', domain:'ml', col:'stats', cat:'Inference', kw:['null hypothesis','alternative','type I error','significance','reject'] },
  { id:'p-value', title:'P-Values', domain:'ml', col:'stats', cat:'Inference', kw:['significance','alpha','reject','test statistic','misinterpretation'] },
  { id:'t-test', title:'T-Test', domain:'ml', col:'stats', cat:'Inference', kw:['student t','two sample','paired','degrees of freedom','small sample'] },
  { id:'anova', title:'ANOVA', domain:'ml', col:'stats', cat:'Inference', kw:['analysis of variance','F-test','between groups','within groups','factor'] },
  { id:'bayesian-inference', title:'Bayesian Inference', domain:'ml', col:'stats', cat:'Bayesian Methods', kw:['posterior','prior','likelihood','update','credible interval'] },
  { id:'conjugate-priors', title:'Conjugate Priors', domain:'ml', col:'stats', cat:'Bayesian Methods', kw:['beta-binomial','normal-normal','gamma-poisson','closed form'] },
  { id:'mcmc', title:'MCMC', domain:'ml', col:'stats', cat:'Bayesian Methods', kw:['markov chain','monte carlo','metropolis','gibbs','sampling','posterior sampling'] },
  { id:'hierarchical', title:'Hierarchical Models', domain:'ml', col:'stats', cat:'Bayesian Methods', kw:['multilevel','random effects','partial pooling','hyperparameters','nested'] },
  { id:'bayesian-regression', title:'Bayesian Regression', domain:'ml', col:'stats', cat:'Bayesian Methods', kw:['posterior distribution','credible interval','predictive','uncertainty'] },
  { id:'ab-testing', title:'A/B Testing', domain:'ml', col:'stats', cat:'Applied', kw:['experiment','control','treatment','conversion','sample size','significance'] },
  { id:'bootstrap', title:'Bootstrap', domain:'ml', col:'stats', cat:'Applied', kw:['resampling','confidence interval','nonparametric','empirical distribution'] },
  { id:'power-analysis', title:'Power Analysis', domain:'ml', col:'stats', cat:'Applied', kw:['sample size','effect size','beta','type II error','statistical power'] },
  { id:'mle-stats', title:'MLE (Statistics)', domain:'ml', col:'stats', cat:'Applied', kw:['maximum likelihood','likelihood function','log-likelihood','fisher information'] },
  { id:'correlation-vs-causation', title:'Correlation vs Causation', domain:'ml', col:'stats', cat:'Applied', kw:['confounding','spurious','causal inference','randomization','DAG'] },
  { id:'simpsons-paradox', title:"Simpson's Paradox", domain:'ml', col:'stats', cat:'Applied', kw:['aggregation','subgroup','reversal','confounding','lurking variable'] },

  // ── ML-Math (38) ────────────────────────────────
  { id:'vectors', title:'Vectors & Matrices', domain:'ml', col:'ml-math', cat:'Foundations', kw:['dot product','matrix multiplication','transpose','linear algebra','eigenvector'] },
  { id:'linear', title:'Linear Regression', domain:'ml', col:'ml-math', cat:'Foundations', kw:['MSE','OLS','weight','bias','least squares','slope'] },
  { id:'logistic', title:'Logistic Regression', domain:'ml', col:'ml-math', cat:'Foundations', kw:['sigmoid','binary classification','decision boundary','log odds'] },
  { id:'gradient', title:'Gradient Descent', domain:'ml', col:'ml-math', cat:'Foundations', kw:['SGD','stochastic','mini-batch','learning rate','convergence','optimization'] },
  { id:'activation', title:'Activation Functions', domain:'ml', col:'ml-math', cat:'Foundations', kw:['sigmoid','relu','tanh','gelu','non-linearity','dead neuron'] },
  { id:'bias-variance', title:'Bias-Variance Tradeoff', domain:'ml', col:'ml-math', cat:'Foundations', kw:['underfitting','overfitting','generalization','complexity','noise'] },
  { id:'loss', title:'Loss Functions', domain:'ml', col:'ml-math', cat:'Training', kw:['MSE','MAE','cross-entropy','BCE','Huber','hinge','focal'] },
  { id:'backprop', title:'Backpropagation', domain:'ml', col:'ml-math', cat:'Training', kw:['chain rule','gradient','backward pass','computational graph','automatic differentiation'] },
  { id:'optimizers', title:'Optimizers', domain:'ml', col:'ml-math', cat:'Training', kw:['adam','adamw','sgd','momentum','rmsprop','adagrad'] },
  { id:'regularization', title:'Regularization', domain:'ml', col:'ml-math', cat:'Training', kw:['L1','L2','lasso','ridge','dropout','weight decay','early stopping'] },
  { id:'batchnorm', title:'Batch Normalization', domain:'ml', col:'ml-math', cat:'Training', kw:['batch norm','layer norm','normalization','internal covariate shift'] },
  { id:'lr-schedule', title:'LR Scheduling', domain:'ml', col:'ml-math', cat:'Training', kw:['cosine decay','warmup','cyclic','step decay','one cycle','annealing'] },
  { id:'weight-init', title:'Weight Initialization', domain:'ml', col:'ml-math', cat:'Training', kw:['xavier','glorot','he','kaiming','variance','fan-in'] },
  { id:'grad-clip', title:'Gradient Clipping', domain:'ml', col:'ml-math', cat:'Training', kw:['gradient explosion','clip norm','clip value','max norm'] },
  { id:'softmax', title:'Softmax', domain:'ml', col:'ml-math', cat:'Core Math', kw:['probability','temperature','logits','classification','distribution','normalize'] },
  { id:'mle', title:'MLE & Gaussian', domain:'ml', col:'ml-math', cat:'Core Math', kw:['maximum likelihood','gaussian','normal distribution','log-likelihood'] },
  { id:'entropy', title:'Entropy', domain:'ml', col:'ml-math', cat:'Core Math', kw:['information','bits','shannon entropy','cross-entropy','surprise','uncertainty'] },
  { id:'kl-div', title:'KL Divergence', domain:'ml', col:'ml-math', cat:'Core Math', kw:['relative entropy','distribution distance','forward KL','reverse KL','ELBO'] },
  { id:'bayes', title:"Bayes' Theorem", domain:'ml', col:'ml-math', cat:'Core Math', kw:['posterior','prior','likelihood','evidence','conditional probability'] },
  { id:'crossval', title:'Cross-Validation', domain:'ml', col:'ml-math', cat:'Core Math', kw:['k-fold','train test split','validation','generalization','stratified'] },
  { id:'metrics', title:'Eval Metrics', domain:'ml', col:'ml-math', cat:'Core Math', kw:['precision','recall','F1','accuracy','ROC','AUC','confusion matrix'] },
  { id:'cosine-sim', title:'Cosine Similarity', domain:'ml', col:'ml-math', cat:'Core Math', kw:['similarity','dot product','angle','embedding distance','vector space'] },
  { id:'cnn', title:'CNN', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['convolution','kernel','filter','stride','padding','pooling','feature map'] },
  { id:'embeddings-ml', title:'Embeddings', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['word2vec','skip-gram','embedding layer','dense vector','semantic'] },
  { id:'attention', title:'Attention', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['self-attention','multi-head','query','key','value','scaled dot-product'] },
  { id:'transformer', title:'Transformer', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['encoder','decoder','positional encoding','feed-forward','residual'] },
  { id:'normalization', title:'Normalization Variants', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['layer norm','RMSNorm','group norm','instance norm'] },
  { id:'rnn', title:'RNN', domain:'ml', col:'ml-math', cat:'Sequence Models', kw:['recurrent','hidden state','sequence','time step','vanishing gradient'] },
  { id:'lstm', title:'LSTM', domain:'ml', col:'ml-math', cat:'Sequence Models', kw:['long short-term memory','forget gate','input gate','output gate','cell state'] },
  { id:'gru', title:'GRU', domain:'ml', col:'ml-math', cat:'Sequence Models', kw:['gated recurrent unit','update gate','reset gate','simplified LSTM'] },
  { id:'pca', title:'PCA', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['principal component','eigenvector','eigenvalue','dimensionality reduction'] },
  { id:'svd', title:'SVD', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['singular value decomposition','matrix factorization','low rank','compression'] },
  { id:'vae', title:'VAE', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['variational autoencoder','ELBO','reparameterization','latent space'] },
  { id:'diffusion', title:'Diffusion Models', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['DDPM','DDIM','noise schedule','denoising','stable diffusion'] },
  { id:'gan', title:'GANs', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['generator','discriminator','minimax','mode collapse','adversarial'] },
  { id:'tokenization-ml', title:'Tokenization (BPE)', domain:'ml', col:'ml-math', cat:'Modern / LLM', kw:['byte pair encoding','subword','vocabulary','merge','sentencepiece'] },
  { id:'lora-ml', title:'LoRA', domain:'ml', col:'ml-math', cat:'Modern / LLM', kw:['low rank adaptation','fine-tuning','parameter efficient','adapter','rank'] },
  { id:'rlhf-ml', title:'RLHF', domain:'ml', col:'ml-math', cat:'Modern / LLM', kw:['reinforcement learning','human feedback','reward model','PPO','alignment'] },

  // ── LLM (30) ────────────────────────────────────
  { id:'tokenization-llm', title:'Tokenization', domain:'ml', col:'llm', cat:'Foundations', kw:['bpe','wordpiece','sentencepiece','byte pair encoding','subword','vocabulary'] },
  { id:'embeddings-llm', title:'Token Embeddings', domain:'ml', col:'llm', cat:'Foundations', kw:['embedding table','lookup','vector','dimension','learned','representation'] },
  { id:'positional-encoding', title:'Positional Encoding', domain:'ml', col:'llm', cat:'Foundations', kw:['sinusoidal','rope','alibi','rotary','position','relative'] },
  { id:'self-attention', title:'Self-Attention', domain:'ml', col:'llm', cat:'Foundations', kw:['query','key','value','qkv','scaled dot product','softmax'] },
  { id:'multi-head-attention', title:'Multi-Head Attention', domain:'ml', col:'llm', cat:'Foundations', kw:['heads','parallel','concat','projection','multi-query','grouped-query'] },
  { id:'feed-forward', title:'Feed-Forward Networks', domain:'ml', col:'llm', cat:'Foundations', kw:['ffn','swiglu','gelu','relu','expansion','hidden dimension','mlp'] },
  { id:'transformer-block', title:'Transformer Block', domain:'ml', col:'llm', cat:'Architecture', kw:['residual','layernorm','prenorm','postnorm','skip connection'] },
  { id:'decoder-only', title:'Decoder-Only Models', domain:'ml', col:'llm', cat:'Architecture', kw:['gpt','causal','autoregressive','mask','llama','next token'] },
  { id:'kv-cache', title:'KV-Cache', domain:'ml', col:'llm', cat:'Architecture', kw:['key value cache','incremental','memory','generation','recompute','prefix'] },
  { id:'context-windows', title:'Context Windows', domain:'ml', col:'llm', cat:'Architecture', kw:['context length','sliding window','sparse attention','rope scaling','long context'] },
  { id:'mixture-of-experts', title:'Mixture of Experts', domain:'ml', col:'llm', cat:'Architecture', kw:['moe','router','expert','sparse','top-k','gating','mixtral'] },
  { id:'scaling-laws', title:'Scaling Laws', domain:'ml', col:'llm', cat:'Architecture', kw:['chinchilla','compute optimal','flops','tokens','parameters','power law'] },
  { id:'pre-training', title:'Pre-Training', domain:'ml', col:'llm', cat:'Training', kw:['next token prediction','causal lm','masked lm','autoregressive','cross entropy'] },
  { id:'fine-tuning', title:'Fine-Tuning', domain:'ml', col:'llm', cat:'Training', kw:['supervised fine-tuning','sft','instruction tuning','catastrophic forgetting'] },
  { id:'lora-qlora', title:'LoRA & QLoRA', domain:'ml', col:'llm', cat:'Training', kw:['low rank','adapter','rank','quantized','4-bit','peft'] },
  { id:'rlhf-llm', title:'RLHF', domain:'ml', col:'llm', cat:'Training', kw:['reinforcement learning','human feedback','reward model','ppo','preference'] },
  { id:'dpo', title:'DPO', domain:'ml', col:'llm', cat:'Training', kw:['direct preference optimization','implicit reward','chosen','rejected','bradley terry'] },
  { id:'data-curation', title:'Data Curation', domain:'ml', col:'llm', cat:'Training', kw:['deduplication','quality filtering','data mixing','synthetic data','contamination'] },
  { id:'decoding-strategies', title:'Decoding Strategies', domain:'ml', col:'llm', cat:'Inference', kw:['greedy','beam search','beam width','best first','argmax'] },
  { id:'sampling', title:'Sampling', domain:'ml', col:'llm', cat:'Inference', kw:['temperature','top-k','top-p','nucleus','softmax','logits','diversity'] },
  { id:'speculative-decoding', title:'Speculative Decoding', domain:'ml', col:'llm', cat:'Inference', kw:['draft model','verification','speedup','acceptance rate','lookahead'] },
  { id:'quantization', title:'Quantization', domain:'ml', col:'llm', cat:'Inference', kw:['int8','int4','fp16','bf16','gptq','awq','gguf','precision'] },
  { id:'kv-cache-opt', title:'KV-Cache Optimization', domain:'ml', col:'llm', cat:'Inference', kw:['paged attention','vllm','block allocation','memory fragmentation'] },
  { id:'batching', title:'Batching & Throughput', domain:'ml', col:'llm', cat:'Inference', kw:['continuous batching','dynamic','prefill','decode','TTFT','TPS'] },
  { id:'prompt-engineering', title:'Prompt Engineering', domain:'ml', col:'llm', cat:'Applications', kw:['system prompt','few-shot','chain of thought','cot','zero-shot'] },
  { id:'rag', title:'RAG', domain:'ml', col:'llm', cat:'Applications', kw:['retrieval augmented generation','chunking','reranking','context window','grounding'] },
  { id:'embedding-search', title:'Embedding Search', domain:'ml', col:'llm', cat:'Applications', kw:['vector similarity','cosine','ann','hnsw','faiss','semantic search'] },
  { id:'function-calling', title:'Function Calling', domain:'ml', col:'llm', cat:'Applications', kw:['tool use','structured output','json mode','schema','api'] },
  { id:'agents', title:'Agents & Planning', domain:'ml', col:'llm', cat:'Applications', kw:['react','tool chain','memory','planning','reflection','autonomous'] },
  { id:'evaluation', title:'Evaluation & Benchmarks', domain:'ml', col:'llm', cat:'Applications', kw:['perplexity','mmlu','humaneval','gsm8k','arena','benchmark'] },

  // ── Markets / Charts (25) ───────────────────────
  { id:'head-and-shoulders', title:'Head & Shoulders', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','top','neckline','left shoulder','bearish'] },
  { id:'inverse-head-and-shoulders', title:'Inverse Head & Shoulders', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','bottom','neckline','bullish','breakout'] },
  { id:'double-top', title:'Double Top', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','M pattern','resistance','two peaks','bearish'] },
  { id:'double-bottom', title:'Double Bottom', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','W pattern','support','two troughs','bullish'] },
  { id:'rounding-bottom', title:'Rounding Bottom', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['saucer','gradual reversal','accumulation','long-term','U-shape'] },
  { id:'bull-flag', title:'Bull Flag', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flag','pole','bullish','consolidation','breakout'] },
  { id:'bear-flag', title:'Bear Flag', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flag','pole','bearish','consolidation','breakdown'] },
  { id:'pennant', title:'Pennant', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','triangle','converging','small','brief','breakout'] },
  { id:'ascending-triangle', title:'Ascending Triangle', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flat top','rising lows','bullish','resistance'] },
  { id:'descending-triangle', title:'Descending Triangle', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flat bottom','falling highs','bearish','support'] },
  { id:'symmetric-triangle', title:'Symmetric Triangle', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['bilateral','converging','neutral','breakout either way','indecision'] },
  { id:'rising-wedge', title:'Rising Wedge', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['bearish','converging up','weakening momentum','breakdown','exhaustion'] },
  { id:'falling-wedge', title:'Falling Wedge', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['bullish','converging down','weakening selling','breakout','accumulation'] },
  { id:'broadening-formation', title:'Broadening Formation', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['megaphone','expanding range','volatility','diverging trendlines'] },
  { id:'rectangle', title:'Rectangle', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['range','consolidation','horizontal','support','resistance'] },
  { id:'doji', title:'Doji', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['indecision','equal open close','cross','neutral','reversal signal'] },
  { id:'hammer', title:'Hammer', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','long lower shadow','bullish','support','rejection'] },
  { id:'engulfing', title:'Engulfing', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','two candle','bullish engulfing','bearish engulfing','momentum shift'] },
  { id:'morning-star', title:'Morning Star', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','three candle','bullish','bottom','gap down'] },
  { id:'evening-star', title:'Evening Star', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','three candle','bearish','top','gap up'] },
  { id:'support-resistance', title:'Support & Resistance', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['levels','horizontal','price memory','floor','ceiling','breakout'] },
  { id:'trendlines', title:'Trendlines', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['diagonal','connecting lows','connecting highs','slope','trend direction'] },
  { id:'channels', title:'Channels', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['parallel trendlines','range','ascending channel','descending channel'] },
  { id:'gaps', title:'Gaps', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['breakaway','runaway','exhaustion','common','opening gap','price void'] },
  { id:'cup-and-handle', title:'Cup & Handle', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['continuation','rounded bottom','handle','breakout','consolidation'] },

  // ── Markets / Indicators (25) ───────────────────
  { id:'sma', title:'Simple Moving Average', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['average','mean','smoothing','trend','crossover','lag'] },
  { id:'ema', title:'Exponential Moving Average', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['weighted','recent','responsive','smoothing factor','crossover'] },
  { id:'wma', title:'Weighted Moving Average', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['linear weight','recent bias','triangle number','smooth'] },
  { id:'dema', title:'Double Exponential MA', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['Patrick Mulloy','reduced lag','double smoothing','fast'] },
  { id:'vwap', title:'VWAP', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['volume weighted','institutional','benchmark','intraday','fair value'] },
  { id:'rsi', title:'Relative Strength Index', domain:'markets', col:'indicators', cat:'Oscillators', kw:['Wilder','overbought','oversold','momentum','divergence'] },
  { id:'stochastic', title:'Stochastic Oscillator', domain:'markets', col:'indicators', cat:'Oscillators', kw:['George Lane','overbought','oversold','crossover','momentum'] },
  { id:'cci', title:'Commodity Channel Index', domain:'markets', col:'indicators', cat:'Oscillators', kw:['Donald Lambert','typical price','mean deviation','overbought','cycle'] },
  { id:'williams-r', title:'Williams %R', domain:'markets', col:'indicators', cat:'Oscillators', kw:['Larry Williams','overbought','oversold','range','fast stochastic'] },
  { id:'roc', title:'Rate of Change', domain:'markets', col:'indicators', cat:'Oscillators', kw:['momentum','percentage change','zero line','speed','acceleration'] },
  { id:'macd', title:'MACD', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Gerald Appel','signal line','histogram','convergence','divergence','crossover'] },
  { id:'adx', title:'Average Directional Index', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Wilder','trend strength','DI+','DI−','directional movement'] },
  { id:'parabolic-sar', title:'Parabolic SAR', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Wilder','stop and reverse','trailing stop','dots','acceleration factor'] },
  { id:'ichimoku', title:'Ichimoku Cloud', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Goichi Hosoda','tenkan','kijun','senkou','kumo','cloud'] },
  { id:'aroon', title:'Aroon', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Tushar Chande','Aroon Up','Aroon Down','new high','new low','trend identification'] },
  { id:'bollinger-bands', title:'Bollinger Bands', domain:'markets', col:'indicators', cat:'Volatility', kw:['John Bollinger','standard deviation','squeeze','expansion','mean reversion'] },
  { id:'atr', title:'Average True Range', domain:'markets', col:'indicators', cat:'Volatility', kw:['Wilder','true range','volatility','position sizing','stop loss'] },
  { id:'keltner-channels', title:'Keltner Channels', domain:'markets', col:'indicators', cat:'Volatility', kw:['Chester Keltner','ATR','EMA','channel','trend','breakout'] },
  { id:'donchian-channels', title:'Donchian Channels', domain:'markets', col:'indicators', cat:'Volatility', kw:['Richard Donchian','highest high','lowest low','turtle traders','breakout'] },
  { id:'standard-deviation', title:'Standard Deviation', domain:'markets', col:'indicators', cat:'Volatility', kw:['sigma','variance','dispersion','normal distribution','volatility measure'] },
  { id:'obv', title:'On-Balance Volume', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['Joe Granville','cumulative volume','confirmation','divergence','breakout'] },
  { id:'accumulation-distribution', title:'Accumulation/Distribution', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['Marc Chaikin','money flow multiplier','CLV','cumulative','smart money'] },
  { id:'mfi', title:'Money Flow Index', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['volume RSI','typical price','money flow','overbought','oversold'] },
  { id:'chaikin-oscillator', title:'Chaikin Oscillator', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['Marc Chaikin','A/D line','3-day EMA','10-day EMA','money flow'] },
  { id:'vwap-bands', title:'VWAP Bands', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['VWAP','standard deviation bands','intraday','institutional levels','mean reversion'] },

  // ── Markets / Psychology (25) ───────────────────
  { id:'confirmation-bias', title:'Confirmation Bias', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['selective','seeking evidence','ignoring contrary','belief','filter'] },
  { id:'anchoring', title:'Anchoring', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['reference point','first number','price anchor','adjustment','52-week high'] },
  { id:'recency-bias', title:'Recency Bias', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['recent events','extrapolation','short memory','trend chasing'] },
  { id:'availability-heuristic', title:'Availability Heuristic', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['vivid memories','media','dramatic events','probability','overweight'] },
  { id:'hindsight-bias', title:'Hindsight Bias', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['knew it all along','predictable','retroactive','narrative fallacy'] },
  { id:'fear-and-greed', title:'Fear & Greed', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['emotion cycle','index','extreme fear','extreme greed','sentiment'] },
  { id:'loss-aversion', title:'Loss Aversion', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['Kahneman','Tversky','prospect theory','losses loom larger','risk averse'] },
  { id:'regret-aversion', title:'Regret Aversion', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['anticipated regret','inaction','omission','paralysis'] },
  { id:'overconfidence', title:'Overconfidence', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['illusion of control','above average','excessive trading','prediction'] },
  { id:'disposition-effect', title:'Disposition Effect', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['sell winners','hold losers','Shefrin','Statman','tax inefficient'] },
  { id:'herd-behavior', title:'Herd Behavior', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['crowd','following','momentum','bubble','crash','collective irrationality'] },
  { id:'fomo', title:'FOMO', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['fear of missing out','buying tops','late entry','anxiety','social media'] },
  { id:'social-proof', title:'Social Proof', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['Cialdini','mimicry','influencer','expert opinion','bandwagon'] },
  { id:'contrarian-thinking', title:'Contrarian Thinking', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['opposite','against the crowd','buy fear','sell greed','value investing'] },
  { id:'information-cascades', title:'Information Cascades', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['sequential decisions','ignore private signal','rational herding','domino'] },
  { id:'sunk-cost-fallacy', title:'Sunk Cost Fallacy', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['throwing good money','past investment','irreversible','doubling down'] },
  { id:'gambler-fallacy', title:"Gambler's Fallacy", domain:'markets', col:'psychology', cat:'Decision Traps', kw:['hot hand','due','independent events','pattern','randomness','streaks'] },
  { id:'framing-effect', title:'Framing Effect', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['presentation','wording','gain frame','loss frame','choice architecture'] },
  { id:'mental-accounting', title:'Mental Accounting', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['Thaler','separate buckets','house money','found money','fungibility'] },
  { id:'status-quo-bias', title:'Status Quo Bias', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['inertia','default option','endowment','change aversion','rebalancing'] },
  { id:'market-sentiment-cycle', title:'Market Sentiment Cycle', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['disbelief','hope','optimism','euphoria','anxiety','panic','capitulation'] },
  { id:'accumulation-distribution-psych', title:'Accumulation & Distribution', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['Wyckoff','smart money','phases','markup','markdown','trading range'] },
  { id:'euphoria-panic', title:'Euphoria & Panic', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['mania','bubble','crash','capitulation','extreme emotion','irrational'] },
  { id:'smart-money-dumb-money', title:'Smart Money vs. Dumb Money', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['institutional','retail','COT report','insider buying','late buyers'] },
  { id:'mean-reversion-psychology', title:'Mean Reversion Psychology', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['regression to mean','overshoot','undershoot','extremes revert','patience'] },

  // ── ML / MLOps (25) ────────────────────────────
  { id:'model-packaging', title:'Model Packaging', domain:'ml', col:'mlops', cat:'Deploy & Serve', kw:['docker','container','ONNX','serialization','artifact','bundle'] },
  { id:'serving-patterns', title:'Serving Patterns', domain:'ml', col:'mlops', cat:'Deploy & Serve', kw:['REST','gRPC','batch','streaming','microservice','endpoint'] },
  { id:'ab-rollout', title:'A/B Rollout', domain:'ml', col:'mlops', cat:'Deploy & Serve', kw:['canary','blue-green','traffic split','progressive','rollback'] },
  { id:'latency-throughput', title:'Latency vs Throughput', domain:'ml', col:'mlops', cat:'Deploy & Serve', kw:['p50','p99','requests per second','SLA','batching','queue'] },
  { id:'gpu-inference', title:'GPU Inference', domain:'ml', col:'mlops', cat:'Deploy & Serve', kw:['CUDA','TensorRT','triton','batching','memory','utilization'] },
  { id:'drift-detection', title:'Drift Detection', domain:'ml', col:'mlops', cat:'Monitor & Observe', kw:['concept drift','data drift','covariate shift','distribution','PSI','KS test'] },
  { id:'model-monitoring', title:'Model Monitoring', domain:'ml', col:'mlops', cat:'Monitor & Observe', kw:['accuracy decay','metrics','dashboard','alerting','performance tracking'] },
  { id:'alerting-slos', title:'Alerting & SLOs', domain:'ml', col:'mlops', cat:'Monitor & Observe', kw:['SLI','SLO','SLA','threshold','pager','error budget'] },
  { id:'shadow-scoring', title:'Shadow Scoring', domain:'ml', col:'mlops', cat:'Monitor & Observe', kw:['dark launch','mirror traffic','offline evaluation','comparison','champion-challenger'] },
  { id:'data-quality', title:'Data Quality', domain:'ml', col:'mlops', cat:'Monitor & Observe', kw:['validation','schema','missing values','outlier','great expectations'] },
  { id:'ml-pipelines', title:'ML Pipelines', domain:'ml', col:'mlops', cat:'Pipeline & Automation', kw:['DAG','Airflow','Kubeflow','step','orchestration','workflow'] },
  { id:'feature-stores', title:'Feature Stores', domain:'ml', col:'mlops', cat:'Pipeline & Automation', kw:['online','offline','Feast','feature engineering','serving','reuse'] },
  { id:'experiment-tracking', title:'Experiment Tracking', domain:'ml', col:'mlops', cat:'Pipeline & Automation', kw:['MLflow','W&B','run','metric','hyperparameter','logging'] },
  { id:'ci-cd-ml', title:'CI/CD for ML', domain:'ml', col:'mlops', cat:'Pipeline & Automation', kw:['continuous integration','testing','deployment','automation','Github Actions'] },
  { id:'orchestration', title:'Orchestration', domain:'ml', col:'mlops', cat:'Pipeline & Automation', kw:['Airflow','Prefect','scheduler','dependency','retry','task graph'] },
  { id:'model-compression', title:'Model Compression', domain:'ml', col:'mlops', cat:'Scale & Optimize', kw:['pruning','distillation','sparsity','smaller model','efficiency'] },
  { id:'quantization', title:'Quantization', domain:'ml', col:'mlops', cat:'Scale & Optimize', kw:['INT8','FP16','mixed precision','calibration','speed','size reduction'] },
  { id:'caching-layers', title:'Caching Layers', domain:'ml', col:'mlops', cat:'Scale & Optimize', kw:['Redis','embedding cache','LRU','feature cache','hit rate'] },
  { id:'auto-scaling', title:'Auto-Scaling', domain:'ml', col:'mlops', cat:'Scale & Optimize', kw:['horizontal','vertical','Kubernetes HPA','queue depth','burst'] },
  { id:'cost-governance', title:'Cost Governance', domain:'ml', col:'mlops', cat:'Scale & Optimize', kw:['GPU cost','spot instances','budget','resource allocation','FinOps'] },
  { id:'model-registry', title:'Model Registry', domain:'ml', col:'mlops', cat:'Governance & Trust', kw:['versioning','staging','production','approval','catalog'] },
  { id:'lineage-tracking', title:'Lineage Tracking', domain:'ml', col:'mlops', cat:'Governance & Trust', kw:['provenance','data lineage','model lineage','DAG','audit trail'] },
  { id:'fairness-audits', title:'Fairness Audits', domain:'ml', col:'mlops', cat:'Governance & Trust', kw:['bias detection','demographic parity','equal opportunity','fairlearn'] },
  { id:'reproducibility', title:'Reproducibility', domain:'ml', col:'mlops', cat:'Governance & Trust', kw:['seed','deterministic','environment','pinning','hash','Docker'] },
  { id:'incident-response', title:'Incident Response', domain:'ml', col:'mlops', cat:'Governance & Trust', kw:['rollback','postmortem','runbook','fallback','circuit breaker'] },

  // ── Markets / Risk & Portfolio (25) ─────────────
  { id:'value-at-risk', title:'Value at Risk', domain:'markets', col:'risk', cat:'Risk Measures', kw:['VaR','confidence level','loss','quantile','tail','parametric'] },
  { id:'expected-shortfall', title:'Expected Shortfall', domain:'markets', col:'risk', cat:'Risk Measures', kw:['CVaR','conditional VaR','tail average','ES','coherent risk'] },
  { id:'volatility-modeling', title:'Volatility Modeling', domain:'markets', col:'risk', cat:'Risk Measures', kw:['GARCH','EWMA','historical vol','implied vol','stochastic'] },
  { id:'correlation-risk', title:'Correlation Risk', domain:'markets', col:'risk', cat:'Risk Measures', kw:['correlation breakdown','contagion','stress','regime change','copula'] },
  { id:'tail-risk', title:'Tail Risk', domain:'markets', col:'risk', cat:'Risk Measures', kw:['fat tails','kurtosis','black swan','extreme event','heavy-tailed'] },
  { id:'mean-variance', title:'Mean-Variance', domain:'markets', col:'risk', cat:'Portfolio Construction', kw:['Markowitz','efficient frontier','optimization','return vs risk','CML'] },
  { id:'risk-parity', title:'Risk Parity', domain:'markets', col:'risk', cat:'Portfolio Construction', kw:['equal risk','all-weather','Bridgewater','inverse volatility','balance'] },
  { id:'factor-models', title:'Factor Models', domain:'markets', col:'risk', cat:'Portfolio Construction', kw:['Fama-French','momentum','value','size','quality','factor loading'] },
  { id:'rebalancing', title:'Rebalancing', domain:'markets', col:'risk', cat:'Portfolio Construction', kw:['drift','threshold','calendar','transaction cost','target weight'] },
  { id:'diversification', title:'Diversification', domain:'markets', col:'risk', cat:'Portfolio Construction', kw:['correlation','asset classes','free lunch','concentration','spread'] },
  { id:'kelly-criterion', title:'Kelly Criterion', domain:'markets', col:'risk', cat:'Position Sizing', kw:['optimal fraction','geometric growth','edge','bankroll','Kelly formula'] },
  { id:'fixed-fractional', title:'Fixed Fractional', domain:'markets', col:'risk', cat:'Position Sizing', kw:['percent risk','fixed percentage','money management','drawdown control'] },
  { id:'volatility-sizing', title:'Volatility Sizing', domain:'markets', col:'risk', cat:'Position Sizing', kw:['ATR sizing','vol-adjusted','normalize risk','position size','adaptive'] },
  { id:'pyramiding', title:'Pyramiding', domain:'markets', col:'risk', cat:'Position Sizing', kw:['adding to winners','scaling in','tiers','profit pyramid','trend following'] },
  { id:'max-position', title:'Max Position', domain:'markets', col:'risk', cat:'Position Sizing', kw:['concentration limit','portfolio weight','risk budget','exposure cap'] },
  { id:'options-hedging', title:'Options Hedging', domain:'markets', col:'risk', cat:'Hedging & Protection', kw:['put','protective put','collar','delta hedge','insurance'] },
  { id:'stop-losses', title:'Stop Losses', domain:'markets', col:'risk', cat:'Hedging & Protection', kw:['trailing stop','ATR stop','time stop','hard stop','max loss'] },
  { id:'pairs-trading', title:'Pairs Trading', domain:'markets', col:'risk', cat:'Hedging & Protection', kw:['stat arb','cointegration','spread','z-score','mean reversion'] },
  { id:'portfolio-insurance', title:'Portfolio Insurance', domain:'markets', col:'risk', cat:'Hedging & Protection', kw:['CPPI','constant proportion','floor','cushion','dynamic hedge'] },
  { id:'currency-hedging', title:'Currency Hedging', domain:'markets', col:'risk', cat:'Hedging & Protection', kw:['FX risk','forward contract','natural hedge','cross-currency'] },
  { id:'return-attribution', title:'Return Attribution', domain:'markets', col:'risk', cat:'Performance & Attribution', kw:['Brinson','allocation effect','selection effect','interaction','decompose'] },
  { id:'benchmark-tracking', title:'Benchmark Tracking', domain:'markets', col:'risk', cat:'Performance & Attribution', kw:['tracking error','index fund','active share','replication'] },
  { id:'alpha-generation', title:'Alpha Generation', domain:'markets', col:'risk', cat:'Performance & Attribution', kw:['excess return','skill','alpha decay','signal','information ratio'] },
  { id:'risk-adjusted-perf', title:'Risk-Adjusted Perf', domain:'markets', col:'risk', cat:'Performance & Attribution', kw:['Sharpe','Sortino','Calmar','Treynor','information ratio'] },
  { id:'drawdown-analysis', title:'Drawdown Analysis', domain:'markets', col:'risk', cat:'Performance & Attribution', kw:['max drawdown','recovery time','underwater','peak to trough','worst case'] },
];

// Unique categories per domain for wave challenges
const CATEGORIES = {};
GAME_TOPICS.forEach(t => {
  if (!CATEGORIES[t.domain]) CATEGORIES[t.domain] = new Set();
  CATEGORIES[t.domain].add(t.cat);
});
Object.keys(CATEGORIES).forEach(d => CATEGORIES[d] = [...CATEGORIES[d]]);

// Cross-domain keywords (appear in 2+ domains) for hard waves
const CROSS_KEYWORDS = (function() {
  const kwMap = {};
  GAME_TOPICS.forEach(t => {
    t.kw.forEach(k => {
      const kl = k.toLowerCase();
      if (!kwMap[kl]) kwMap[kl] = new Set();
      kwMap[kl].add(t.domain);
    });
  });
  return Object.entries(kwMap)
    .filter(([, domains]) => domains.size >= 2)
    .map(([kw, domains]) => ({ kw, domains: [...domains] }));
})();
