/* ───────────────────────────────────────────────────
   Pattern Drift — Game Data
   All 252 topics from 9 collections, 3 domains
   ─────────────────────────────────────────────────── */

const DOMAINS = {
  ml:      { label: 'Machine Learning', color: '#4fc3f7', glow: 'rgba(79,195,247,' },
  markets: { label: 'Markets',          color: '#81c784', glow: 'rgba(129,199,132,' },
  poetry:  { label: 'Poetry',           color: '#f48fb1', glow: 'rgba(244,143,177,' }
};

const COLLECTIONS = {
  'stats':        { domain: 'ml',      label: 'Statistics' },
  'ml-math':      { domain: 'ml',      label: 'ML & Math' },
  'llm':          { domain: 'ml',      label: 'LLM' },
  'charts':       { domain: 'markets', label: 'Chart Patterns' },
  'indicators':   { domain: 'markets', label: 'Indicators' },
  'psychology':   { domain: 'markets', label: 'Psychology' },
  'forms':        { domain: 'poetry',  label: 'Poetic Forms' },
  'sound':        { domain: 'poetry',  label: 'Sound & Meter' },
  'rhetoric':     { domain: 'poetry',  label: 'Rhetoric' }
};

const GAME_TOPICS = [

  // ── Stats (34) ──────────────────────────────────
  { id:'mean-median', title:'Mean, Median & Mode', domain:'ml', col:'stats', cat:'Descriptive Stats', kw:['average','central tendency','median','mode','mean'] },
  { id:'variance-std', title:'Variance & Std Dev', domain:'ml', col:'stats', cat:'Descriptive Stats', kw:['spread','dispersion','standard deviation','variance','range'] },
  { id:'percentiles', title:'Percentiles & Quartiles', domain:'ml', col:'stats', cat:'Descriptive Stats', kw:['quartile','percentile','IQR','box plot','outlier'] },
  { id:'correlation', title:'Correlation', domain:'ml', col:'stats', cat:'Descriptive Stats', kw:['pearson','spearman','r-value','linear relationship','scatter plot'] },
  { id:'covariance', title:'Covariance', domain:'ml', col:'stats', cat:'Descriptive Stats', kw:['joint variability','covariance matrix','positive','negative'] },
  { id:'prob-basics', title:'Probability Basics', domain:'ml', col:'stats', cat:'Probability', kw:['event','sample space','union','intersection','complement','axioms'] },
  { id:'conditional', title:'Conditional Probability', domain:'ml', col:'stats', cat:'Probability', kw:['given','bayes','posterior','likelihood','prior','conditional'] },
  { id:'independence', title:'Independence', domain:'ml', col:'stats', cat:'Probability', kw:['independent events','joint probability','marginal','multiplication rule'] },
  { id:'combinatorics', title:'Combinatorics', domain:'ml', col:'stats', cat:'Probability', kw:['permutation','combination','factorial','counting','binomial coefficient'] },
  { id:'law-large-numbers', title:'Law of Large Numbers', domain:'ml', col:'stats', cat:'Probability', kw:['convergence','sample mean','expected value','weak law','strong law'] },
  { id:'normal', title:'Normal Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['gaussian','bell curve','z-score','standard normal','CLT'] },
  { id:'binomial', title:'Binomial Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['bernoulli','trials','success','failure','binary outcome'] },
  { id:'poisson', title:'Poisson Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['rare events','rate','lambda','count data','arrivals'] },
  { id:'exponential', title:'Exponential Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['waiting time','memoryless','decay','half-life','survival'] },
  { id:'uniform', title:'Uniform Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['equal probability','flat','rectangular','continuous','discrete'] },
  { id:'beta', title:'Beta Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['prior','proportion','bayesian','alpha','conjugate'] },
  { id:'chi-squared', title:'Chi-Squared Distribution', domain:'ml', col:'stats', cat:'Distributions', kw:['goodness of fit','degrees of freedom','test statistic','categorical'] },
  { id:'clt', title:'Central Limit Theorem', domain:'ml', col:'stats', cat:'Inference', kw:['sample mean','normal approximation','sampling distribution','standard error'] },
  { id:'confidence', title:'Confidence Intervals', domain:'ml', col:'stats', cat:'Inference', kw:['margin of error','interval estimate','z-interval','t-interval','coverage'] },
  { id:'hypothesis', title:'Hypothesis Testing', domain:'ml', col:'stats', cat:'Inference', kw:['null hypothesis','alternative','type I error','significance','reject'] },
  { id:'p-value', title:'P-Values', domain:'ml', col:'stats', cat:'Inference', kw:['significance','alpha','reject','test statistic','misinterpretation'] },
  { id:'t-test', title:'T-Test', domain:'ml', col:'stats', cat:'Inference', kw:['student t','two sample','paired','degrees of freedom','small sample'] },
  { id:'anova', title:'ANOVA', domain:'ml', col:'stats', cat:'Inference', kw:['analysis of variance','F-test','between groups','within groups','factor'] },
  { id:'bayesian-inference', title:'Bayesian Inference', domain:'ml', col:'stats', cat:'Bayesian Methods', kw:['posterior','prior','likelihood','update','credible interval'] },
  { id:'conjugate-priors', title:'Conjugate Priors', domain:'ml', col:'stats', cat:'Bayesian Methods', kw:['beta-binomial','normal-normal','gamma-poisson','closed form'] },
  { id:'mcmc', title:'MCMC', domain:'ml', col:'stats', cat:'Bayesian Methods', kw:['markov chain','monte carlo','metropolis','gibbs','sampling','posterior sampling'] },
  { id:'hierarchical', title:'Hierarchical Models', domain:'ml', col:'stats', cat:'Bayesian Methods', kw:['multilevel','random effects','partial pooling','hyperparameters','nested'] },
  { id:'bayesian-regression', title:'Bayesian Regression', domain:'ml', col:'stats', cat:'Bayesian Methods', kw:['posterior distribution','credible interval','predictive','uncertainty'] },
  { id:'ab-testing', title:'A/B Testing', domain:'ml', col:'stats', cat:'Applied', kw:['experiment','control','treatment','conversion','sample size','significance'] },
  { id:'bootstrap', title:'Bootstrap', domain:'ml', col:'stats', cat:'Applied', kw:['resampling','confidence interval','nonparametric','empirical distribution'] },
  { id:'power-analysis', title:'Power Analysis', domain:'ml', col:'stats', cat:'Applied', kw:['sample size','effect size','beta','type II error','statistical power'] },
  { id:'mle-stats', title:'MLE (Statistics)', domain:'ml', col:'stats', cat:'Applied', kw:['maximum likelihood','likelihood function','log-likelihood','fisher information'] },
  { id:'correlation-vs-causation', title:'Correlation vs Causation', domain:'ml', col:'stats', cat:'Applied', kw:['confounding','spurious','causal inference','randomization','DAG'] },
  { id:'simpsons-paradox', title:"Simpson's Paradox", domain:'ml', col:'stats', cat:'Applied', kw:['aggregation','subgroup','reversal','confounding','lurking variable'] },

  // ── ML-Math (38) ────────────────────────────────
  { id:'vectors', title:'Vectors & Matrices', domain:'ml', col:'ml-math', cat:'Foundations', kw:['dot product','matrix multiplication','transpose','linear algebra','eigenvector'] },
  { id:'linear', title:'Linear Regression', domain:'ml', col:'ml-math', cat:'Foundations', kw:['MSE','OLS','weight','bias','least squares','slope'] },
  { id:'logistic', title:'Logistic Regression', domain:'ml', col:'ml-math', cat:'Foundations', kw:['sigmoid','binary classification','decision boundary','log odds'] },
  { id:'gradient', title:'Gradient Descent', domain:'ml', col:'ml-math', cat:'Foundations', kw:['SGD','stochastic','mini-batch','learning rate','convergence','optimization'] },
  { id:'activation', title:'Activation Functions', domain:'ml', col:'ml-math', cat:'Foundations', kw:['sigmoid','relu','tanh','gelu','non-linearity','dead neuron'] },
  { id:'bias-variance', title:'Bias-Variance Tradeoff', domain:'ml', col:'ml-math', cat:'Foundations', kw:['underfitting','overfitting','generalization','complexity','noise'] },
  { id:'loss', title:'Loss Functions', domain:'ml', col:'ml-math', cat:'Training', kw:['MSE','MAE','cross-entropy','BCE','Huber','hinge','focal'] },
  { id:'backprop', title:'Backpropagation', domain:'ml', col:'ml-math', cat:'Training', kw:['chain rule','gradient','backward pass','computational graph','automatic differentiation'] },
  { id:'optimizers', title:'Optimizers', domain:'ml', col:'ml-math', cat:'Training', kw:['adam','adamw','sgd','momentum','rmsprop','adagrad'] },
  { id:'regularization', title:'Regularization', domain:'ml', col:'ml-math', cat:'Training', kw:['L1','L2','lasso','ridge','dropout','weight decay','early stopping'] },
  { id:'batchnorm', title:'Batch Normalization', domain:'ml', col:'ml-math', cat:'Training', kw:['batch norm','layer norm','normalization','internal covariate shift'] },
  { id:'lr-schedule', title:'LR Scheduling', domain:'ml', col:'ml-math', cat:'Training', kw:['cosine decay','warmup','cyclic','step decay','one cycle','annealing'] },
  { id:'weight-init', title:'Weight Initialization', domain:'ml', col:'ml-math', cat:'Training', kw:['xavier','glorot','he','kaiming','variance','fan-in'] },
  { id:'grad-clip', title:'Gradient Clipping', domain:'ml', col:'ml-math', cat:'Training', kw:['gradient explosion','clip norm','clip value','max norm'] },
  { id:'softmax', title:'Softmax', domain:'ml', col:'ml-math', cat:'Core Math', kw:['probability','temperature','logits','classification','distribution','normalize'] },
  { id:'mle', title:'MLE & Gaussian', domain:'ml', col:'ml-math', cat:'Core Math', kw:['maximum likelihood','gaussian','normal distribution','log-likelihood'] },
  { id:'entropy', title:'Entropy', domain:'ml', col:'ml-math', cat:'Core Math', kw:['information','bits','shannon entropy','cross-entropy','surprise','uncertainty'] },
  { id:'kl-div', title:'KL Divergence', domain:'ml', col:'ml-math', cat:'Core Math', kw:['relative entropy','distribution distance','forward KL','reverse KL','ELBO'] },
  { id:'bayes', title:"Bayes' Theorem", domain:'ml', col:'ml-math', cat:'Core Math', kw:['posterior','prior','likelihood','evidence','conditional probability'] },
  { id:'crossval', title:'Cross-Validation', domain:'ml', col:'ml-math', cat:'Core Math', kw:['k-fold','train test split','validation','generalization','stratified'] },
  { id:'metrics', title:'Eval Metrics', domain:'ml', col:'ml-math', cat:'Core Math', kw:['precision','recall','F1','accuracy','ROC','AUC','confusion matrix'] },
  { id:'cosine-sim', title:'Cosine Similarity', domain:'ml', col:'ml-math', cat:'Core Math', kw:['similarity','dot product','angle','embedding distance','vector space'] },
  { id:'cnn', title:'CNN', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['convolution','kernel','filter','stride','padding','pooling','feature map'] },
  { id:'embeddings-ml', title:'Embeddings', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['word2vec','skip-gram','embedding layer','dense vector','semantic'] },
  { id:'attention', title:'Attention', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['self-attention','multi-head','query','key','value','scaled dot-product'] },
  { id:'transformer', title:'Transformer', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['encoder','decoder','positional encoding','feed-forward','residual'] },
  { id:'normalization', title:'Normalization Variants', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['layer norm','RMSNorm','group norm','instance norm'] },
  { id:'rnn', title:'RNN', domain:'ml', col:'ml-math', cat:'Sequence Models', kw:['recurrent','hidden state','sequence','time step','vanishing gradient'] },
  { id:'lstm', title:'LSTM', domain:'ml', col:'ml-math', cat:'Sequence Models', kw:['long short-term memory','forget gate','input gate','output gate','cell state'] },
  { id:'gru', title:'GRU', domain:'ml', col:'ml-math', cat:'Sequence Models', kw:['gated recurrent unit','update gate','reset gate','simplified LSTM'] },
  { id:'pca', title:'PCA', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['principal component','eigenvector','eigenvalue','dimensionality reduction'] },
  { id:'svd', title:'SVD', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['singular value decomposition','matrix factorization','low rank','compression'] },
  { id:'vae', title:'VAE', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['variational autoencoder','ELBO','reparameterization','latent space'] },
  { id:'diffusion', title:'Diffusion Models', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['DDPM','DDIM','noise schedule','denoising','stable diffusion'] },
  { id:'gan', title:'GANs', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['generator','discriminator','minimax','mode collapse','adversarial'] },
  { id:'tokenization-ml', title:'Tokenization (BPE)', domain:'ml', col:'ml-math', cat:'Modern / LLM', kw:['byte pair encoding','subword','vocabulary','merge','sentencepiece'] },
  { id:'lora-ml', title:'LoRA', domain:'ml', col:'ml-math', cat:'Modern / LLM', kw:['low rank adaptation','fine-tuning','parameter efficient','adapter','rank'] },
  { id:'rlhf-ml', title:'RLHF', domain:'ml', col:'ml-math', cat:'Modern / LLM', kw:['reinforcement learning','human feedback','reward model','PPO','alignment'] },

  // ── LLM (30) ────────────────────────────────────
  { id:'tokenization-llm', title:'Tokenization', domain:'ml', col:'llm', cat:'Foundations', kw:['bpe','wordpiece','sentencepiece','byte pair encoding','subword','vocabulary'] },
  { id:'embeddings-llm', title:'Token Embeddings', domain:'ml', col:'llm', cat:'Foundations', kw:['embedding table','lookup','vector','dimension','learned','representation'] },
  { id:'positional-encoding', title:'Positional Encoding', domain:'ml', col:'llm', cat:'Foundations', kw:['sinusoidal','rope','alibi','rotary','position','relative'] },
  { id:'self-attention', title:'Self-Attention', domain:'ml', col:'llm', cat:'Foundations', kw:['query','key','value','qkv','scaled dot product','softmax'] },
  { id:'multi-head-attention', title:'Multi-Head Attention', domain:'ml', col:'llm', cat:'Foundations', kw:['heads','parallel','concat','projection','multi-query','grouped-query'] },
  { id:'feed-forward', title:'Feed-Forward Networks', domain:'ml', col:'llm', cat:'Foundations', kw:['ffn','swiglu','gelu','relu','expansion','hidden dimension','mlp'] },
  { id:'transformer-block', title:'Transformer Block', domain:'ml', col:'llm', cat:'Architecture', kw:['residual','layernorm','prenorm','postnorm','skip connection'] },
  { id:'decoder-only', title:'Decoder-Only Models', domain:'ml', col:'llm', cat:'Architecture', kw:['gpt','causal','autoregressive','mask','llama','next token'] },
  { id:'kv-cache', title:'KV-Cache', domain:'ml', col:'llm', cat:'Architecture', kw:['key value cache','incremental','memory','generation','recompute','prefix'] },
  { id:'context-windows', title:'Context Windows', domain:'ml', col:'llm', cat:'Architecture', kw:['context length','sliding window','sparse attention','rope scaling','long context'] },
  { id:'mixture-of-experts', title:'Mixture of Experts', domain:'ml', col:'llm', cat:'Architecture', kw:['moe','router','expert','sparse','top-k','gating','mixtral'] },
  { id:'scaling-laws', title:'Scaling Laws', domain:'ml', col:'llm', cat:'Architecture', kw:['chinchilla','compute optimal','flops','tokens','parameters','power law'] },
  { id:'pre-training', title:'Pre-Training', domain:'ml', col:'llm', cat:'Training', kw:['next token prediction','causal lm','masked lm','autoregressive','cross entropy'] },
  { id:'fine-tuning', title:'Fine-Tuning', domain:'ml', col:'llm', cat:'Training', kw:['supervised fine-tuning','sft','instruction tuning','catastrophic forgetting'] },
  { id:'lora-qlora', title:'LoRA & QLoRA', domain:'ml', col:'llm', cat:'Training', kw:['low rank','adapter','rank','quantized','4-bit','peft'] },
  { id:'rlhf-llm', title:'RLHF', domain:'ml', col:'llm', cat:'Training', kw:['reinforcement learning','human feedback','reward model','ppo','preference'] },
  { id:'dpo', title:'DPO', domain:'ml', col:'llm', cat:'Training', kw:['direct preference optimization','implicit reward','chosen','rejected','bradley terry'] },
  { id:'data-curation', title:'Data Curation', domain:'ml', col:'llm', cat:'Training', kw:['deduplication','quality filtering','data mixing','synthetic data','contamination'] },
  { id:'decoding-strategies', title:'Decoding Strategies', domain:'ml', col:'llm', cat:'Inference', kw:['greedy','beam search','beam width','best first','argmax'] },
  { id:'sampling', title:'Sampling', domain:'ml', col:'llm', cat:'Inference', kw:['temperature','top-k','top-p','nucleus','softmax','logits','diversity'] },
  { id:'speculative-decoding', title:'Speculative Decoding', domain:'ml', col:'llm', cat:'Inference', kw:['draft model','verification','speedup','acceptance rate','lookahead'] },
  { id:'quantization', title:'Quantization', domain:'ml', col:'llm', cat:'Inference', kw:['int8','int4','fp16','bf16','gptq','awq','gguf','precision'] },
  { id:'kv-cache-opt', title:'KV-Cache Optimization', domain:'ml', col:'llm', cat:'Inference', kw:['paged attention','vllm','block allocation','memory fragmentation'] },
  { id:'batching', title:'Batching & Throughput', domain:'ml', col:'llm', cat:'Inference', kw:['continuous batching','dynamic','prefill','decode','TTFT','TPS'] },
  { id:'prompt-engineering', title:'Prompt Engineering', domain:'ml', col:'llm', cat:'Applications', kw:['system prompt','few-shot','chain of thought','cot','zero-shot'] },
  { id:'rag', title:'RAG', domain:'ml', col:'llm', cat:'Applications', kw:['retrieval augmented generation','chunking','reranking','context window','grounding'] },
  { id:'embedding-search', title:'Embedding Search', domain:'ml', col:'llm', cat:'Applications', kw:['vector similarity','cosine','ann','hnsw','faiss','semantic search'] },
  { id:'function-calling', title:'Function Calling', domain:'ml', col:'llm', cat:'Applications', kw:['tool use','structured output','json mode','schema','api'] },
  { id:'agents', title:'Agents & Planning', domain:'ml', col:'llm', cat:'Applications', kw:['react','tool chain','memory','planning','reflection','autonomous'] },
  { id:'evaluation', title:'Evaluation & Benchmarks', domain:'ml', col:'llm', cat:'Applications', kw:['perplexity','mmlu','humaneval','gsm8k','arena','benchmark'] },

  // ── Markets / Charts (25) ───────────────────────
  { id:'head-and-shoulders', title:'Head & Shoulders', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','top','neckline','left shoulder','bearish'] },
  { id:'inverse-head-and-shoulders', title:'Inverse Head & Shoulders', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','bottom','neckline','bullish','breakout'] },
  { id:'double-top', title:'Double Top', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','M pattern','resistance','two peaks','bearish'] },
  { id:'double-bottom', title:'Double Bottom', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','W pattern','support','two troughs','bullish'] },
  { id:'rounding-bottom', title:'Rounding Bottom', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['saucer','gradual reversal','accumulation','long-term','U-shape'] },
  { id:'bull-flag', title:'Bull Flag', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flag','pole','bullish','consolidation','breakout'] },
  { id:'bear-flag', title:'Bear Flag', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flag','pole','bearish','consolidation','breakdown'] },
  { id:'pennant', title:'Pennant', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','triangle','converging','small','brief','breakout'] },
  { id:'ascending-triangle', title:'Ascending Triangle', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flat top','rising lows','bullish','resistance'] },
  { id:'descending-triangle', title:'Descending Triangle', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flat bottom','falling highs','bearish','support'] },
  { id:'symmetric-triangle', title:'Symmetric Triangle', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['bilateral','converging','neutral','breakout either way','indecision'] },
  { id:'rising-wedge', title:'Rising Wedge', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['bearish','converging up','weakening momentum','breakdown','exhaustion'] },
  { id:'falling-wedge', title:'Falling Wedge', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['bullish','converging down','weakening selling','breakout','accumulation'] },
  { id:'broadening-formation', title:'Broadening Formation', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['megaphone','expanding range','volatility','diverging trendlines'] },
  { id:'rectangle', title:'Rectangle', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['range','consolidation','horizontal','support','resistance'] },
  { id:'doji', title:'Doji', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['indecision','equal open close','cross','neutral','reversal signal'] },
  { id:'hammer', title:'Hammer', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','long lower shadow','bullish','support','rejection'] },
  { id:'engulfing', title:'Engulfing', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','two candle','bullish engulfing','bearish engulfing','momentum shift'] },
  { id:'morning-star', title:'Morning Star', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','three candle','bullish','bottom','gap down'] },
  { id:'evening-star', title:'Evening Star', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','three candle','bearish','top','gap up'] },
  { id:'support-resistance', title:'Support & Resistance', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['levels','horizontal','price memory','floor','ceiling','breakout'] },
  { id:'trendlines', title:'Trendlines', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['diagonal','connecting lows','connecting highs','slope','trend direction'] },
  { id:'channels', title:'Channels', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['parallel trendlines','range','ascending channel','descending channel'] },
  { id:'gaps', title:'Gaps', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['breakaway','runaway','exhaustion','common','opening gap','price void'] },
  { id:'cup-and-handle', title:'Cup & Handle', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['continuation','rounded bottom','handle','breakout','consolidation'] },

  // ── Markets / Indicators (25) ───────────────────
  { id:'sma', title:'Simple Moving Average', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['average','mean','smoothing','trend','crossover','lag'] },
  { id:'ema', title:'Exponential Moving Average', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['weighted','recent','responsive','smoothing factor','crossover'] },
  { id:'wma', title:'Weighted Moving Average', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['linear weight','recent bias','triangle number','smooth'] },
  { id:'dema', title:'Double Exponential MA', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['Patrick Mulloy','reduced lag','double smoothing','fast'] },
  { id:'vwap', title:'VWAP', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['volume weighted','institutional','benchmark','intraday','fair value'] },
  { id:'rsi', title:'Relative Strength Index', domain:'markets', col:'indicators', cat:'Oscillators', kw:['Wilder','overbought','oversold','momentum','divergence'] },
  { id:'stochastic', title:'Stochastic Oscillator', domain:'markets', col:'indicators', cat:'Oscillators', kw:['George Lane','overbought','oversold','crossover','momentum'] },
  { id:'cci', title:'Commodity Channel Index', domain:'markets', col:'indicators', cat:'Oscillators', kw:['Donald Lambert','typical price','mean deviation','overbought','cycle'] },
  { id:'williams-r', title:'Williams %R', domain:'markets', col:'indicators', cat:'Oscillators', kw:['Larry Williams','overbought','oversold','range','fast stochastic'] },
  { id:'roc', title:'Rate of Change', domain:'markets', col:'indicators', cat:'Oscillators', kw:['momentum','percentage change','zero line','speed','acceleration'] },
  { id:'macd', title:'MACD', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Gerald Appel','signal line','histogram','convergence','divergence','crossover'] },
  { id:'adx', title:'Average Directional Index', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Wilder','trend strength','DI+','DI−','directional movement'] },
  { id:'parabolic-sar', title:'Parabolic SAR', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Wilder','stop and reverse','trailing stop','dots','acceleration factor'] },
  { id:'ichimoku', title:'Ichimoku Cloud', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Goichi Hosoda','tenkan','kijun','senkou','kumo','cloud'] },
  { id:'aroon', title:'Aroon', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Tushar Chande','Aroon Up','Aroon Down','new high','new low','trend identification'] },
  { id:'bollinger-bands', title:'Bollinger Bands', domain:'markets', col:'indicators', cat:'Volatility', kw:['John Bollinger','standard deviation','squeeze','expansion','mean reversion'] },
  { id:'atr', title:'Average True Range', domain:'markets', col:'indicators', cat:'Volatility', kw:['Wilder','true range','volatility','position sizing','stop loss'] },
  { id:'keltner-channels', title:'Keltner Channels', domain:'markets', col:'indicators', cat:'Volatility', kw:['Chester Keltner','ATR','EMA','channel','trend','breakout'] },
  { id:'donchian-channels', title:'Donchian Channels', domain:'markets', col:'indicators', cat:'Volatility', kw:['Richard Donchian','highest high','lowest low','turtle traders','breakout'] },
  { id:'standard-deviation', title:'Standard Deviation', domain:'markets', col:'indicators', cat:'Volatility', kw:['sigma','variance','dispersion','normal distribution','volatility measure'] },
  { id:'obv', title:'On-Balance Volume', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['Joe Granville','cumulative volume','confirmation','divergence','breakout'] },
  { id:'accumulation-distribution', title:'Accumulation/Distribution', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['Marc Chaikin','money flow multiplier','CLV','cumulative','smart money'] },
  { id:'mfi', title:'Money Flow Index', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['volume RSI','typical price','money flow','overbought','oversold'] },
  { id:'chaikin-oscillator', title:'Chaikin Oscillator', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['Marc Chaikin','A/D line','3-day EMA','10-day EMA','money flow'] },
  { id:'vwap-bands', title:'VWAP Bands', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['VWAP','standard deviation bands','intraday','institutional levels','mean reversion'] },

  // ── Markets / Psychology (25) ───────────────────
  { id:'confirmation-bias', title:'Confirmation Bias', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['selective','seeking evidence','ignoring contrary','belief','filter'] },
  { id:'anchoring', title:'Anchoring', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['reference point','first number','price anchor','adjustment','52-week high'] },
  { id:'recency-bias', title:'Recency Bias', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['recent events','extrapolation','short memory','trend chasing'] },
  { id:'availability-heuristic', title:'Availability Heuristic', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['vivid memories','media','dramatic events','probability','overweight'] },
  { id:'hindsight-bias', title:'Hindsight Bias', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['knew it all along','predictable','retroactive','narrative fallacy'] },
  { id:'fear-and-greed', title:'Fear & Greed', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['emotion cycle','index','extreme fear','extreme greed','sentiment'] },
  { id:'loss-aversion', title:'Loss Aversion', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['Kahneman','Tversky','prospect theory','losses loom larger','risk averse'] },
  { id:'regret-aversion', title:'Regret Aversion', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['anticipated regret','inaction','omission','paralysis'] },
  { id:'overconfidence', title:'Overconfidence', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['illusion of control','above average','excessive trading','prediction'] },
  { id:'disposition-effect', title:'Disposition Effect', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['sell winners','hold losers','Shefrin','Statman','tax inefficient'] },
  { id:'herd-behavior', title:'Herd Behavior', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['crowd','following','momentum','bubble','crash','collective irrationality'] },
  { id:'fomo', title:'FOMO', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['fear of missing out','buying tops','late entry','anxiety','social media'] },
  { id:'social-proof', title:'Social Proof', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['Cialdini','mimicry','influencer','expert opinion','bandwagon'] },
  { id:'contrarian-thinking', title:'Contrarian Thinking', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['opposite','against the crowd','buy fear','sell greed','value investing'] },
  { id:'information-cascades', title:'Information Cascades', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['sequential decisions','ignore private signal','rational herding','domino'] },
  { id:'sunk-cost-fallacy', title:'Sunk Cost Fallacy', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['throwing good money','past investment','irreversible','doubling down'] },
  { id:'gambler-fallacy', title:"Gambler's Fallacy", domain:'markets', col:'psychology', cat:'Decision Traps', kw:['hot hand','due','independent events','pattern','randomness','streaks'] },
  { id:'framing-effect', title:'Framing Effect', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['presentation','wording','gain frame','loss frame','choice architecture'] },
  { id:'mental-accounting', title:'Mental Accounting', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['Thaler','separate buckets','house money','found money','fungibility'] },
  { id:'status-quo-bias', title:'Status Quo Bias', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['inertia','default option','endowment','change aversion','rebalancing'] },
  { id:'market-sentiment-cycle', title:'Market Sentiment Cycle', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['disbelief','hope','optimism','euphoria','anxiety','panic','capitulation'] },
  { id:'accumulation-distribution-psych', title:'Accumulation & Distribution', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['Wyckoff','smart money','phases','markup','markdown','trading range'] },
  { id:'euphoria-panic', title:'Euphoria & Panic', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['mania','bubble','crash','capitulation','extreme emotion','irrational'] },
  { id:'smart-money-dumb-money', title:'Smart Money vs. Dumb Money', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['institutional','retail','COT report','insider buying','late buyers'] },
  { id:'mean-reversion-psychology', title:'Mean Reversion Psychology', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['regression to mean','overshoot','undershoot','extremes revert','patience'] },

  // ── Poetry / Forms (25) ─────────────────────────
  { id:'shakespearean-sonnet', title:'Shakespearean Sonnet', domain:'poetry', col:'forms', cat:'Sonnets', kw:['english sonnet','14 lines','iambic pentameter','ABAB CDCD EFEF GG','couplet'] },
  { id:'petrarchan-sonnet', title:'Petrarchan Sonnet', domain:'poetry', col:'forms', cat:'Sonnets', kw:['italian sonnet','octave','sestet','ABBAABBA','volta','turn'] },
  { id:'spenserian-sonnet', title:'Spenserian Sonnet', domain:'poetry', col:'forms', cat:'Sonnets', kw:['interlocking rhyme','ABAB BCBC CDCD EE','Edmund Spenser'] },
  { id:'modern-sonnet', title:'Modern Sonnet', domain:'poetry', col:'forms', cat:'Sonnets', kw:['contemporary','slant rhyme','free sonnet','14 lines','loose form'] },
  { id:'crown-of-sonnets', title:'Crown of Sonnets', domain:'poetry', col:'forms', cat:'Sonnets', kw:['corona','seven sonnets','linked','last line first line','heroic crown'] },
  { id:'villanelle', title:'Villanelle', domain:'poetry', col:'forms', cat:'Fixed Forms', kw:['19 lines','5 tercets','quatrain','refrain','ABA','Dylan Thomas','repetition'] },
  { id:'sestina', title:'Sestina', domain:'poetry', col:'forms', cat:'Fixed Forms', kw:['39 lines','6 stanzas','end words','rotation','envoi','spiral'] },
  { id:'pantoum', title:'Pantoum', domain:'poetry', col:'forms', cat:'Fixed Forms', kw:['malay','interlocking quatrains','repeated lines','circular','hypnotic'] },
  { id:'ghazal', title:'Ghazal', domain:'poetry', col:'forms', cat:'Fixed Forms', kw:['arabic','persian','urdu','couplets','radif','qafia','longing'] },
  { id:'rondeau', title:'Rondeau', domain:'poetry', col:'forms', cat:'Fixed Forms', kw:['french','15 lines','rentrement','refrain','AABBA','In Flanders Fields'] },
  { id:'haiku', title:'Haiku', domain:'poetry', col:'forms', cat:'Short Forms', kw:['japanese','5-7-5','syllable','kireji','kigo','season','nature','juxtaposition'] },
  { id:'tanka', title:'Tanka', domain:'poetry', col:'forms', cat:'Short Forms', kw:['japanese','5-7-5-7-7','31 syllables','waka','upper phrase','pivot'] },
  { id:'limerick', title:'Limerick', domain:'poetry', col:'forms', cat:'Short Forms', kw:['AABBA','5 lines','humor','anapestic','Edward Lear','comic'] },
  { id:'epigram', title:'Epigram', domain:'poetry', col:'forms', cat:'Short Forms', kw:['wit','brevity','paradox','satirical','Oscar Wilde','aphorism'] },
  { id:'couplet', title:'Couplet', domain:'poetry', col:'forms', cat:'Short Forms', kw:['two lines','rhyme','heroic couplet','iambic pentameter','Pope'] },
  { id:'ballad', title:'Ballad', domain:'poetry', col:'forms', cat:'Narrative & Long Forms', kw:['story','ABCB','quatrain','folk','narrative','refrain','oral tradition'] },
  { id:'ode', title:'Ode', domain:'poetry', col:'forms', cat:'Narrative & Long Forms', kw:['praise','Pindaric','Horatian','irregular','strophe','Keats'] },
  { id:'elegy', title:'Elegy', domain:'poetry', col:'forms', cat:'Narrative & Long Forms', kw:['mourning','grief','loss','lament','consolation','pastoral elegy'] },
  { id:'epic', title:'Epic', domain:'poetry', col:'forms', cat:'Narrative & Long Forms', kw:['long narrative','hero','invocation','in medias res','Homer','Milton'] },
  { id:'dramatic-monologue', title:'Dramatic Monologue', domain:'poetry', col:'forms', cat:'Narrative & Long Forms', kw:['speaker','persona','audience','Browning','revelation','mask'] },
  { id:'free-verse', title:'Free Verse', domain:'poetry', col:'forms', cat:'Free & Experimental', kw:['no fixed meter','no rhyme scheme','Whitman','vers libre','breath','organic'] },
  { id:'blank-verse', title:'Blank Verse', domain:'poetry', col:'forms', cat:'Free & Experimental', kw:['unrhymed iambic pentameter','Shakespeare','Milton','Paradise Lost','dramatic'] },
  { id:'prose-poetry', title:'Prose Poetry', domain:'poetry', col:'forms', cat:'Free & Experimental', kw:['no line breaks','paragraph','Baudelaire','hybrid','compression'] },
  { id:'concrete-poetry', title:'Concrete Poetry', domain:'poetry', col:'forms', cat:'Free & Experimental', kw:['visual','shape','typography','space','pattern','calligram'] },
  { id:'acrostic', title:'Acrostic', domain:'poetry', col:'forms', cat:'Free & Experimental', kw:['hidden message','first letters','names','dedication','puzzle','wordplay'] },

  // ── Poetry / Sound (25) ─────────────────────────
  { id:'iambic-pentameter', title:'Iambic Pentameter', domain:'poetry', col:'sound', cat:'Meter & Rhythm', kw:['iamb','da-DUM','5 feet','10 syllables','unstressed stressed','Shakespeare'] },
  { id:'trochaic-meter', title:'Trochaic Meter', domain:'poetry', col:'sound', cat:'Meter & Rhythm', kw:['trochee','DUM-da','stressed-unstressed','falling rhythm','Longfellow'] },
  { id:'anapestic-meter', title:'Anapestic Meter', domain:'poetry', col:'sound', cat:'Meter & Rhythm', kw:['anapest','da-da-DUM','galloping','comic','limerick','triple meter'] },
  { id:'dactylic-meter', title:'Dactylic Meter', domain:'poetry', col:'sound', cat:'Meter & Rhythm', kw:['dactyl','DUM-da-da','falling triple','hexameter','Homer','classical'] },
  { id:'spondee-pyrrhic', title:'Spondee & Pyrrhic', domain:'poetry', col:'sound', cat:'Meter & Rhythm', kw:['spondee','pyrrhic','two stressed','two unstressed','substitution'] },
  { id:'perfect-rhyme', title:'Perfect Rhyme', domain:'poetry', col:'sound', cat:'Rhyme', kw:['exact rhyme','full rhyme','true rhyme','cat/hat','masculine'] },
  { id:'slant-rhyme', title:'Slant Rhyme', domain:'poetry', col:'sound', cat:'Rhyme', kw:['near rhyme','half rhyme','off rhyme','imperfect','Dickinson'] },
  { id:'eye-rhyme', title:'Eye Rhyme', domain:'poetry', col:'sound', cat:'Rhyme', kw:['visual rhyme','spelling','love/move','cough/through','sight rhyme'] },
  { id:'internal-rhyme', title:'Internal Rhyme', domain:'poetry', col:'sound', cat:'Rhyme', kw:['mid-line','within line','Poe','dreary/weary','leonine rhyme'] },
  { id:'feminine-masculine', title:'Feminine & Masculine Rhyme', domain:'poetry', col:'sound', cat:'Rhyme', kw:['single rhyme','double rhyme','stressed','unstressed','falling'] },
  { id:'alliteration', title:'Alliteration', domain:'poetry', col:'sound', cat:'Sound Repetition', kw:['initial consonant','beginning sounds','Peter Piper','Anglo-Saxon','emphasis'] },
  { id:'assonance', title:'Assonance', domain:'poetry', col:'sound', cat:'Sound Repetition', kw:['vowel repetition','internal vowels','fleet feet','mood','musicality'] },
  { id:'consonance', title:'Consonance', domain:'poetry', col:'sound', cat:'Sound Repetition', kw:['consonant repetition','internal consonants','pitter patter','texture'] },
  { id:'onomatopoeia', title:'Onomatopoeia', domain:'poetry', col:'sound', cat:'Sound Repetition', kw:['sound words','buzz','hiss','crash','imitation','sensory'] },
  { id:'euphony-cacophony', title:'Euphony & Cacophony', domain:'poetry', col:'sound', cat:'Sound Repetition', kw:['pleasant sound','harsh sound','smooth','rough','liquid consonants'] },
  { id:'caesura', title:'Caesura', domain:'poetry', col:'sound', cat:'Rhythmic Devices', kw:['pause','mid-line break','punctuation','breathing','dramatic pause'] },
  { id:'enjambment', title:'Enjambment', domain:'poetry', col:'sound', cat:'Rhythmic Devices', kw:['run-on line','continuation','overflow','line break','momentum','tension'] },
  { id:'end-stopped', title:'End-Stopped Lines', domain:'poetry', col:'sound', cat:'Rhythmic Devices', kw:['pause at end','period','comma','complete thought','closure'] },
  { id:'syncopation', title:'Syncopation', domain:'poetry', col:'sound', cat:'Rhythmic Devices', kw:['off-beat','unexpected stress','jazz','disruption','counterpoint'] },
  { id:'sprung-rhythm', title:'Sprung Rhythm', domain:'poetry', col:'sound', cat:'Rhythmic Devices', kw:['Hopkins','stressed syllables','variable unstressed','natural speech'] },
  { id:'refrain', title:'Refrain', domain:'poetry', col:'sound', cat:'Musical Structures', kw:['repeated line','chorus','recurring','villanelle','ballad','accumulation'] },
  { id:'anaphora-sound', title:'Anaphora', domain:'poetry', col:'sound', cat:'Musical Structures', kw:['beginning repetition','I have a dream','Whitman','insistence','parallel beginning'] },
  { id:'epistrophe', title:'Epistrophe', domain:'poetry', col:'sound', cat:'Musical Structures', kw:['ending repetition','end of line','of the people','closure','echo'] },
  { id:'parallelism', title:'Parallelism', domain:'poetry', col:'sound', cat:'Musical Structures', kw:['parallel structure','balanced','syntax','Whitman','Psalms','catalogue'] },
  { id:'cadence', title:'Cadence', domain:'poetry', col:'sound', cat:'Musical Structures', kw:['rhythm of prose','natural rhythm','falling','rising','speech rhythm'] },

  // ── Poetry / Rhetoric (25) ─────────────────────
  { id:'metaphor', title:'Metaphor', domain:'poetry', col:'rhetoric', cat:'Comparison & Analogy', kw:['comparison','identity','tenor','vehicle','implied','direct'] },
  { id:'simile', title:'Simile', domain:'poetry', col:'rhetoric', cat:'Comparison & Analogy', kw:['like','as','comparison','explicit','Homer','epic simile'] },
  { id:'analogy', title:'Analogy', domain:'poetry', col:'rhetoric', cat:'Comparison & Analogy', kw:['extended comparison','proportion','A is to B','reasoning','explanation'] },
  { id:'conceit', title:'Conceit', domain:'poetry', col:'rhetoric', cat:'Comparison & Analogy', kw:['extended metaphor','Donne','Petrarchan','elaborated','compass','unlikely'] },
  { id:'allegory', title:'Allegory', domain:'poetry', col:'rhetoric', cat:'Comparison & Analogy', kw:['sustained metaphor','Animal Farm','moral','hidden meaning','narrative'] },
  { id:'metonymy', title:'Metonymy', domain:'poetry', col:'rhetoric', cat:'Substitution & Renaming', kw:['associated name','the Crown','the pen','substitution','adjacency'] },
  { id:'synecdoche', title:'Synecdoche', domain:'poetry', col:'rhetoric', cat:'Substitution & Renaming', kw:['part for whole','whole for part','hands','all hands','sails'] },
  { id:'personification', title:'Personification', domain:'poetry', col:'rhetoric', cat:'Substitution & Renaming', kw:['human qualities','animate','Death','Time','nature speaks'] },
  { id:'apostrophe-rhet', title:'Apostrophe', domain:'poetry', col:'rhetoric', cat:'Substitution & Renaming', kw:['direct address','O Death','absent person','abstract','invocation'] },
  { id:'periphrasis', title:'Periphrasis', domain:'poetry', col:'rhetoric', cat:'Substitution & Renaming', kw:['roundabout','circumlocution','kenning','whale-road','ring-giver'] },
  { id:'irony', title:'Irony', domain:'poetry', col:'rhetoric', cat:'Contrast & Contradiction', kw:['opposite meaning','verbal','dramatic','situational','sarcasm','Socratic'] },
  { id:'oxymoron', title:'Oxymoron', domain:'poetry', col:'rhetoric', cat:'Contrast & Contradiction', kw:['contradictory terms','bitter sweet','living dead','deafening silence'] },
  { id:'paradox', title:'Paradox', domain:'poetry', col:'rhetoric', cat:'Contrast & Contradiction', kw:['self-contradiction','truth','impossible','Donne','war is peace'] },
  { id:'antithesis', title:'Antithesis', domain:'poetry', col:'rhetoric', cat:'Contrast & Contradiction', kw:['balanced opposites','parallel','contrast','Dickens','best of times'] },
  { id:'litotes', title:'Litotes', domain:'poetry', col:'rhetoric', cat:'Contrast & Contradiction', kw:['double negative','not bad','not unlike','understatement','affirmation'] },
  { id:'hyperbole', title:'Hyperbole', domain:'poetry', col:'rhetoric', cat:'Amplification & Emphasis', kw:['exaggeration','overstatement','million times','died laughing','emphasis'] },
  { id:'understatement', title:'Understatement', domain:'poetry', col:'rhetoric', cat:'Amplification & Emphasis', kw:['meiosis','less than expected','deliberate minimize','Titanic'] },
  { id:'climax-rhet', title:'Climax (Gradatio)', domain:'poetry', col:'rhetoric', cat:'Amplification & Emphasis', kw:['ascending order','building','crescendo','least to greatest','escalation'] },
  { id:'anadiplosis', title:'Anadiplosis', domain:'poetry', col:'rhetoric', cat:'Amplification & Emphasis', kw:['end-beginning','linking','chain','last word becomes first','Yoda'] },
  { id:'chiasmus', title:'Chiasmus', domain:'poetry', col:'rhetoric', cat:'Amplification & Emphasis', kw:['ABBA','reversed parallel','crossing','Kennedy','mirror'] },
  { id:'imagery', title:'Imagery', domain:'poetry', col:'rhetoric', cat:'Imagery & Sensory', kw:['sensory detail','visual','auditory','tactile','gustatory','olfactory'] },
  { id:'synesthesia', title:'Synesthesia', domain:'poetry', col:'rhetoric', cat:'Imagery & Sensory', kw:['mixed senses','loud color','sweet sound','blue note','cross-sensory'] },
  { id:'symbol', title:'Symbol', domain:'poetry', col:'rhetoric', cat:'Imagery & Sensory', kw:['concrete for abstract','rose','dove','skull','flag','recurring'] },
  { id:'motif', title:'Motif', domain:'poetry', col:'rhetoric', cat:'Imagery & Sensory', kw:['recurring element','pattern','theme','blood in Macbeth','water'] },
  { id:'juxtaposition', title:'Juxtaposition', domain:'poetry', col:'rhetoric', cat:'Imagery & Sensory', kw:['side by side','contrast','comparison','placing together','beauty and ugliness'] }
];

// Unique categories per domain for wave challenges
const CATEGORIES = {};
GAME_TOPICS.forEach(t => {
  if (!CATEGORIES[t.domain]) CATEGORIES[t.domain] = new Set();
  CATEGORIES[t.domain].add(t.cat);
});
Object.keys(CATEGORIES).forEach(d => CATEGORIES[d] = [...CATEGORIES[d]]);

// Cross-domain keywords (appear in 2+ domains) for hard waves
const CROSS_KEYWORDS = (function() {
  const kwMap = {};
  GAME_TOPICS.forEach(t => {
    t.kw.forEach(k => {
      const kl = k.toLowerCase();
      if (!kwMap[kl]) kwMap[kl] = new Set();
      kwMap[kl].add(t.domain);
    });
  });
  return Object.entries(kwMap)
    .filter(([, domains]) => domains.size >= 2)
    .map(([kw, domains]) => ({ kw, domains: [...domains] }));
})();
