/* ───────────────────────────────────────────────────
   Pattern Drift — Game Data
   All 257 topics from 9 collections, 2 domains
   ─────────────────────────────────────────────────── */

const DOMAINS = {
  ml:      { label: 'Machine Learning', color: '#4fc3f7', glow: 'rgba(79,195,247,' },
  markets: { label: 'Markets',          color: '#81c784', glow: 'rgba(129,199,132,' }
};

const COLLECTIONS = {
  'stats':        { domain: 'ml',      label: 'The Toolkit' },
  'ml-math':      { domain: 'ml',      label: 'ML & Math' },
  'llm':          { domain: 'ml',      label: 'LLM' },
  'charts':       { domain: 'markets', label: 'Chart Patterns' },
  'indicators':   { domain: 'markets', label: 'Indicators' },
  'psychology':   { domain: 'markets', label: 'Psychology' },
  'mlops':        { domain: 'ml',      label: 'MLOps' },
  'timeseries':   { domain: 'ml',      label: 'Timeseries' },
  'risk':         { domain: 'markets', label: 'Risk & Portfolio' }
};

const GAME_TOPICS = [

  // ── stats (39) ──────────────────────────────
  { id:'confusion-matrix', title:'Confusion Matrix & Classification Metrics', domain:'ml', col:'stats', cat:'Evaluate Your Model', kw:['precision','recall','f1','accuracy','true positive'] },
  { id:'roc-auc', title:'ROC & AUC Curves', domain:'ml', col:'stats', cat:'Evaluate Your Model', kw:['receiver operating characteristic','area under curve','threshold','TPR','FPR'] },
  { id:'regression-metrics', title:'Regression Metrics', domain:'ml', col:'stats', cat:'Evaluate Your Model', kw:['MAE','RMSE','R-squared','adjusted R²','mean absolute error'] },
  { id:'cross-validation', title:'Cross-Validation Done Right', domain:'ml', col:'stats', cat:'Evaluate Your Model', kw:['k-fold','stratified','time series split','data leakage','train test split'] },
  { id:'comparing-runs', title:'Comparing Model Runs', domain:'ml', col:'stats', cat:'Evaluate Your Model', kw:['paired t-test','McNemar','Wilcoxon','statistical significance','model comparison'] },
  { id:'learning-curves', title:'Learning Curves & Overfitting', domain:'ml', col:'stats', cat:'Evaluate Your Model', kw:['training curve','validation curve','overfitting','underfitting','early stopping'] },
  { id:'shap-values', title:'SHAP Values', domain:'ml', col:'stats', cat:'Understand Your Features', kw:['shapley','feature importance','explainability','force plot','summary plot'] },
  { id:'permutation-importance', title:'Permutation Importance', domain:'ml', col:'stats', cat:'Understand Your Features', kw:['feature importance','shuffle','model-agnostic','correlated features','baseline'] },
  { id:'pdp-ice', title:'Partial Dependence & ICE', domain:'ml', col:'stats', cat:'Understand Your Features', kw:['partial dependence plot','individual conditional expectation','marginal effect','interaction','feature effect'] },
  { id:'feature-correlation', title:'Feature Correlation & Multicollinearity', domain:'ml', col:'stats', cat:'Understand Your Features', kw:['heatmap','VIF','variance inflation factor','collinearity','correlation matrix'] },
  { id:'information-gain', title:'Information Gain & Mutual Information', domain:'ml', col:'stats', cat:'Understand Your Features', kw:['entropy','mutual information','feature selection','nonlinear','KL divergence'] },
  { id:'distribution-shape', title:'Distribution Shape', domain:'ml', col:'stats', cat:'Analyze Your Data', kw:['skewness','kurtosis','QQ plot','normal','histogram'] },
  { id:'outlier-detection', title:'Outlier Detection', domain:'ml', col:'stats', cat:'Analyze Your Data', kw:['IQR','z-score','isolation forest','DBSCAN','anomaly'] },
  { id:'missing-data', title:'Missing Data Strategies', domain:'ml', col:'stats', cat:'Analyze Your Data', kw:['imputation','MICE','KNN impute','MCAR','MAR'] },
  { id:'data-drift', title:'Data Drift & Distribution Shift', domain:'ml', col:'stats', cat:'Analyze Your Data', kw:['PSI','population stability index','KS test','Kolmogorov-Smirnov','concept drift'] },
  { id:'class-imbalance', title:'Sampling & Class Imbalance', domain:'ml', col:'stats', cat:'Analyze Your Data', kw:['SMOTE','undersampling','oversampling','stratification','class weights'] },
  { id:'sharpe-ratio', title:'Sharpe Ratio & Risk-Adjusted Returns', domain:'ml', col:'stats', cat:'Backtest & Validate', kw:['Sharpe','Sortino','Calmar','risk-adjusted','volatility'] },
  { id:'max-drawdown', title:'Maximum Drawdown & Recovery', domain:'ml', col:'stats', cat:'Backtest & Validate', kw:['drawdown','peak to trough','recovery time','worst case','underwater'] },
  { id:'walk-forward', title:'Walk-Forward Validation', domain:'ml', col:'stats', cat:'Backtest & Validate', kw:['rolling window','anchored','expanding window','time series','look-ahead bias'] },
  { id:'monte-carlo', title:'Monte Carlo Simulation', domain:'ml', col:'stats', cat:'Backtest & Validate', kw:['simulation','random paths','confidence','bootstrapped returns','path dependence'] },
  { id:'survivorship-bias', title:'Survivorship & Look-Ahead Bias', domain:'ml', col:'stats', cat:'Backtest & Validate', kw:['survivorship','look-ahead','selection bias','delisted','backtest traps'] },
  { id:'confidence-intervals', title:'Confidence Intervals', domain:'ml', col:'stats', cat:'Make Decisions', kw:['confidence level','margin of error','bootstrap CI','parametric','width'] },
  { id:'bootstrap-methods', title:'Bootstrap Methods', domain:'ml', col:'stats', cat:'Make Decisions', kw:['resampling','nonparametric','percentile method','BCa','empirical distribution'] },
  { id:'bayesian-ab', title:'Bayesian A/B Testing', domain:'ml', col:'stats', cat:'Make Decisions', kw:['credible interval','posterior','prior','probability of improvement','early stopping'] },
  { id:'effect-size', title:'Effect Size & Practical Significance', domain:'ml', col:'stats', cat:'Make Decisions', kw:['Cohen\'s d','practical significance','meaningful difference','small medium large','overlap'] },
  { id:'power-analysis', title:'Power Analysis', domain:'ml', col:'stats', cat:'Make Decisions', kw:['sample size','MDE','minimum detectable effect','type II error','statistical power'] },
  { id:'hypothesis-testing', title:'Hypothesis Testing & p-values', domain:'ml', col:'stats', cat:'Statistical Foundations', kw:['null hypothesis','alternative hypothesis','p-value','significance','alpha'] },
  { id:'stat-tests', title:'Choosing the Right Statistical Test', domain:'ml', col:'stats', cat:'Statistical Foundations', kw:['t-test','chi-square','ANOVA','Mann-Whitney','Wilcoxon'] },
  { id:'clt-sampling', title:'Central Limit Theorem & Sampling', domain:'ml', col:'stats', cat:'Statistical Foundations', kw:['central limit theorem','CLT','sampling distribution','standard error','sample mean'] },
  { id:'correlation-causation', title:'Correlation, Causation & Simpson\'s Paradox', domain:'ml', col:'stats', cat:'Statistical Foundations', kw:['correlation','causation','confounder','Simpson paradox','spurious correlation'] },
  { id:'eda-workflow', title:'Exploratory Data Analysis (EDA)', domain:'ml', col:'stats', cat:'Data Analytics', kw:['EDA','describe','summary statistics','data profiling','histogram'] },
  { id:'groupby-aggregation', title:'GroupBy, Pivot & Aggregation', domain:'ml', col:'stats', cat:'Data Analytics', kw:['groupby','pivot table','aggregation','split-apply-combine','crosstab'] },
  { id:'cohort-retention', title:'Cohort & Retention Analysis', domain:'ml', col:'stats', cat:'Data Analytics', kw:['cohort','retention','churn','retention curve','heatmap'] },
  { id:'funnel-analysis', title:'Funnel & Conversion Analysis', domain:'ml', col:'stats', cat:'Data Analytics', kw:['funnel','conversion rate','drop-off','landing page','checkout'] },
  { id:'sklearn-eval', title:'scikit-learn Evaluation Suite', domain:'ml', col:'stats', cat:'Python Power Tools', kw:['classification_report','cross_val_score','learning_curve','confusion_matrix','GridSearchCV'] },
  { id:'shap-library', title:'SHAP Library', domain:'ml', col:'stats', cat:'Python Power Tools', kw:['shap','TreeExplainer','force_plot','summary_plot','waterfall'] },
  { id:'optuna', title:'Optuna', domain:'ml', col:'stats', cat:'Python Power Tools', kw:['hyperparameter','optimization','pruning','study','TPE'] },
  { id:'pandas-ta', title:'pandas-ta & yfinance', domain:'ml', col:'stats', cat:'Python Power Tools', kw:['technical indicators','yfinance','market data','SMA','RSI'] },
  { id:'scipy-statsmodels', title:'scipy.stats & statsmodels', domain:'ml', col:'stats', cat:'Python Power Tools', kw:['scipy','statsmodels','statistical tests','ttest_ind','OLS'] },

  // ── ml-math (38) ──────────────────────────────
  { id:'vectors', title:'Vectors & Matrices', domain:'ml', col:'ml-math', cat:'Foundations', kw:['dot product','matrix multiplication','transpose','linear algebra','eigenvector'] },
  { id:'linear', title:'Linear Regression', domain:'ml', col:'ml-math', cat:'Foundations', kw:['MSE','OLS','weight','bias','least squares'] },
  { id:'logistic', title:'Logistic Regression', domain:'ml', col:'ml-math', cat:'Foundations', kw:['sigmoid','binary classification','decision boundary','log odds','logit'] },
  { id:'gradient', title:'Gradient Descent', domain:'ml', col:'ml-math', cat:'Foundations', kw:['SGD','stochastic','mini-batch','learning rate','convergence'] },
  { id:'activation', title:'Activation Functions', domain:'ml', col:'ml-math', cat:'Foundations', kw:['sigmoid','relu','tanh','gelu','silu'] },
  { id:'bias-variance', title:'Bias-Variance Tradeoff', domain:'ml', col:'ml-math', cat:'Foundations', kw:['underfitting','overfitting','generalization','complexity','U-curve'] },
  { id:'loss', title:'Loss Functions', domain:'ml', col:'ml-math', cat:'Training', kw:['MSE','MAE','cross-entropy','BCE','Huber'] },
  { id:'backprop', title:'Backpropagation', domain:'ml', col:'ml-math', cat:'Training', kw:['chain rule','gradient','backward pass','computational graph','automatic differentiation'] },
  { id:'optimizers', title:'Optimizers', domain:'ml', col:'ml-math', cat:'Training', kw:['adam','adamw','sgd','momentum','rmsprop'] },
  { id:'regularization', title:'Regularization', domain:'ml', col:'ml-math', cat:'Training', kw:['L1','L2','lasso','ridge','dropout'] },
  { id:'batchnorm', title:'Batch Normalization', domain:'ml', col:'ml-math', cat:'Training', kw:['batch norm','layer norm','normalization','internal covariate shift','gamma'] },
  { id:'lr-schedule', title:'LR Scheduling', domain:'ml', col:'ml-math', cat:'Training', kw:['cosine decay','warmup','cyclic','step decay','one cycle'] },
  { id:'weight-init', title:'Weight Initialization', domain:'ml', col:'ml-math', cat:'Training', kw:['xavier','glorot','he','kaiming','initialization'] },
  { id:'grad-clip', title:'Gradient Clipping', domain:'ml', col:'ml-math', cat:'Training', kw:['gradient explosion','clip norm','clip value','max norm','gradient scaling'] },
  { id:'softmax', title:'Softmax', domain:'ml', col:'ml-math', cat:'Core Math', kw:['probability','temperature','logits','classification','distribution'] },
  { id:'mle', title:'MLE & Gaussian', domain:'ml', col:'ml-math', cat:'Core Math', kw:['maximum likelihood','gaussian','normal distribution','log-likelihood','parameter estimation'] },
  { id:'entropy', title:'Entropy', domain:'ml', col:'ml-math', cat:'Core Math', kw:['information','bits','shannon entropy','cross-entropy','surprise'] },
  { id:'kl-div', title:'KL Divergence', domain:'ml', col:'ml-math', cat:'Core Math', kw:['relative entropy','distribution distance','forward KL','reverse KL','ELBO'] },
  { id:'bayes', title:'Bayes\' Theorem', domain:'ml', col:'ml-math', cat:'Core Math', kw:['posterior','prior','likelihood','evidence','conditional probability'] },
  { id:'crossval', title:'Cross-Validation', domain:'ml', col:'ml-math', cat:'Core Math', kw:['k-fold','train test split','validation','generalization','stratified'] },
  { id:'metrics', title:'Eval Metrics', domain:'ml', col:'ml-math', cat:'Core Math', kw:['precision','recall','F1','accuracy','ROC'] },
  { id:'cosine-sim', title:'Cosine Similarity', domain:'ml', col:'ml-math', cat:'Core Math', kw:['similarity','dot product','angle','embedding distance','vector space'] },
  { id:'cnn', title:'CNN', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['convolution','kernel','filter','stride','padding'] },
  { id:'embeddings', title:'Embeddings', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['word2vec','skip-gram','embedding layer','dense vector','semantic'] },
  { id:'attention', title:'Attention', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['self-attention','multi-head','query','key','value'] },
  { id:'transformer', title:'Transformer', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['encoder','decoder','positional encoding','feed-forward','residual'] },
  { id:'normalization', title:'Normalization Variants', domain:'ml', col:'ml-math', cat:'Deep Learning', kw:['layer norm','RMSNorm','group norm','instance norm','LLaMA'] },
  { id:'rnn', title:'RNN', domain:'ml', col:'ml-math', cat:'Sequence Models', kw:['recurrent','hidden state','sequence','time step','BPTT'] },
  { id:'lstm', title:'LSTM', domain:'ml', col:'ml-math', cat:'Sequence Models', kw:['long short-term memory','forget gate','input gate','output gate','cell state'] },
  { id:'gru', title:'GRU', domain:'ml', col:'ml-math', cat:'Sequence Models', kw:['gated recurrent unit','update gate','reset gate','simplified LSTM'] },
  { id:'pca', title:'PCA', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['principal component','eigenvector','eigenvalue','covariance','dimensionality reduction'] },
  { id:'svd', title:'SVD', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['singular value decomposition','matrix factorization','low rank','recommender','compression'] },
  { id:'vae', title:'VAE', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['variational autoencoder','ELBO','reparameterization','latent space','encoder decoder'] },
  { id:'diffusion', title:'Diffusion Models', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['DDPM','DDIM','noise schedule','denoising','stable diffusion'] },
  { id:'gan', title:'GANs', domain:'ml', col:'ml-math', cat:'Generative & Prob.', kw:['generator','discriminator','minimax','mode collapse','wasserstein'] },
  { id:'tokenization', title:'Tokenization (BPE)', domain:'ml', col:'ml-math', cat:'Modern / LLM', kw:['byte pair encoding','subword','vocabulary','merge','token'] },
  { id:'lora', title:'LoRA', domain:'ml', col:'ml-math', cat:'Modern / LLM', kw:['low rank adaptation','fine-tuning','parameter efficient','adapter','rank'] },
  { id:'rlhf', title:'RLHF', domain:'ml', col:'ml-math', cat:'Modern / LLM', kw:['reinforcement learning','human feedback','reward model','PPO','DPO'] },

  // ── llm (30) ──────────────────────────────
  { id:'tokenization', title:'Tokenization', domain:'ml', col:'llm', cat:'Foundations', kw:['bpe','wordpiece','sentencepiece','byte pair encoding','subword'] },
  { id:'embeddings', title:'Token Embeddings', domain:'ml', col:'llm', cat:'Foundations', kw:['embedding table','lookup','vector','dimension','learned'] },
  { id:'positional-encoding', title:'Positional Encoding', domain:'ml', col:'llm', cat:'Foundations', kw:['sinusoidal','rope','alibi','rotary','position'] },
  { id:'self-attention', title:'Self-Attention', domain:'ml', col:'llm', cat:'Foundations', kw:['query','key','value','qkv','scaled dot product'] },
  { id:'multi-head-attention', title:'Multi-Head Attention', domain:'ml', col:'llm', cat:'Foundations', kw:['heads','parallel','concat','projection','multi-query'] },
  { id:'feed-forward', title:'Feed-Forward Networks', domain:'ml', col:'llm', cat:'Foundations', kw:['ffn','swiglu','gelu','relu','expansion'] },
  { id:'transformer-block', title:'Transformer Block', domain:'ml', col:'llm', cat:'Architecture', kw:['residual','layernorm','prenorm','postnorm','block'] },
  { id:'decoder-only', title:'Decoder-Only Models', domain:'ml', col:'llm', cat:'Architecture', kw:['gpt','causal','autoregressive','mask','llama'] },
  { id:'kv-cache', title:'KV-Cache', domain:'ml', col:'llm', cat:'Architecture', kw:['key value cache','incremental','memory','generation','recompute'] },
  { id:'context-windows', title:'Context Windows', domain:'ml', col:'llm', cat:'Architecture', kw:['context length','sliding window','sparse attention','rope scaling','ntk'] },
  { id:'mixture-of-experts', title:'Mixture of Experts', domain:'ml', col:'llm', cat:'Architecture', kw:['moe','router','expert','sparse','top-k'] },
  { id:'scaling-laws', title:'Scaling Laws', domain:'ml', col:'llm', cat:'Architecture', kw:['chinchilla','compute optimal','flops','tokens','parameters'] },
  { id:'pre-training', title:'Pre-Training', domain:'ml', col:'llm', cat:'Training', kw:['next token prediction','causal lm','masked lm','autoregressive','loss'] },
  { id:'fine-tuning', title:'Fine-Tuning', domain:'ml', col:'llm', cat:'Training', kw:['supervised fine-tuning','sft','instruction tuning','chat','catastrophic forgetting'] },
  { id:'lora-qlora', title:'LoRA & QLoRA', domain:'ml', col:'llm', cat:'Training', kw:['low rank','adapter','rank','alpha','quantized'] },
  { id:'rlhf', title:'RLHF', domain:'ml', col:'llm', cat:'Training', kw:['reinforcement learning','human feedback','reward model','ppo','preference'] },
  { id:'dpo', title:'DPO', domain:'ml', col:'llm', cat:'Training', kw:['direct preference optimization','implicit reward','chosen','rejected','bradley terry'] },
  { id:'data-curation', title:'Data Curation', domain:'ml', col:'llm', cat:'Training', kw:['deduplication','quality filtering','data mixing','ratio','synthetic data'] },
  { id:'decoding-strategies', title:'Decoding Strategies', domain:'ml', col:'llm', cat:'Inference', kw:['greedy','beam search','beam width','best first','argmax'] },
  { id:'sampling', title:'Sampling', domain:'ml', col:'llm', cat:'Inference', kw:['temperature','top-k','top-p','nucleus','softmax'] },
  { id:'speculative-decoding', title:'Speculative Decoding', domain:'ml', col:'llm', cat:'Inference', kw:['draft model','verification','speedup','acceptance rate','lookahead'] },
  { id:'quantization', title:'Quantization', domain:'ml', col:'llm', cat:'Inference', kw:['int8','int4','fp16','bf16','gptq'] },
  { id:'kv-cache-opt', title:'KV-Cache Optimization', domain:'ml', col:'llm', cat:'Inference', kw:['paged attention','vllm','block allocation','memory fragmentation','prefix caching'] },
  { id:'batching', title:'Batching & Throughput', domain:'ml', col:'llm', cat:'Inference', kw:['continuous batching','dynamic','prefill','decode','TTFT'] },
  { id:'prompt-engineering', title:'Prompt Engineering', domain:'ml', col:'llm', cat:'Applications', kw:['system prompt','few-shot','chain of thought','cot','zero-shot'] },
  { id:'rag', title:'RAG', domain:'ml', col:'llm', cat:'Applications', kw:['retrieval augmented generation','chunking','reranking','context window','grounding'] },
  { id:'embedding-search', title:'Embedding Search', domain:'ml', col:'llm', cat:'Applications', kw:['vector similarity','cosine','ann','hnsw','faiss'] },
  { id:'function-calling', title:'Function Calling', domain:'ml', col:'llm', cat:'Applications', kw:['tool use','structured output','json mode','schema','api'] },
  { id:'agents', title:'Agents & Planning', domain:'ml', col:'llm', cat:'Applications', kw:['react','tool chain','memory','planning','reflection'] },
  { id:'evaluation', title:'Evaluation & Benchmarks', domain:'ml', col:'llm', cat:'Applications', kw:['perplexity','mmlu','humaneval','gsm8k','arena'] },

  // ── mlops (25) ──────────────────────────────
  { id:'model-packaging', title:'Model Packaging & Containers', domain:'ml', col:'mlops', cat:'Deploy & Serve', kw:['docker','container','ONNX','pickle','MLflow'] },
  { id:'serving-patterns', title:'Serving Patterns', domain:'ml', col:'mlops', cat:'Deploy & Serve', kw:['REST','gRPC','batch','streaming','online'] },
  { id:'ab-rollout', title:'A/B & Canary Rollouts', domain:'ml', col:'mlops', cat:'Deploy & Serve', kw:['canary','blue-green','traffic split','rollback','gradual'] },
  { id:'latency-throughput', title:'Latency & Throughput', domain:'ml', col:'mlops', cat:'Deploy & Serve', kw:['p50','p99','requests per second','batching','async'] },
  { id:'gpu-inference', title:'GPU Inference', domain:'ml', col:'mlops', cat:'Deploy & Serve', kw:['GPU','TensorRT','CUDA','Triton','multi-model'] },
  { id:'drift-detection', title:'Drift Detection in Production', domain:'ml', col:'mlops', cat:'Monitor & Observe', kw:['PSI','KS test','data drift','concept drift','covariate shift'] },
  { id:'model-monitoring', title:'Model Monitoring Dashboards', domain:'ml', col:'mlops', cat:'Monitor & Observe', kw:['Grafana','Prometheus','metrics','accuracy decay','feature distributions'] },
  { id:'alerting-slos', title:'Alerting & SLOs', domain:'ml', col:'mlops', cat:'Monitor & Observe', kw:['SLO','SLA','SLI','error budget','latency budget'] },
  { id:'shadow-scoring', title:'Shadow Mode & Champion/Challenger', domain:'ml', col:'mlops', cat:'Monitor & Observe', kw:['shadow','champion','challenger','dark launch','comparison'] },
  { id:'data-quality', title:'Data Quality Gates', domain:'ml', col:'mlops', cat:'Monitor & Observe', kw:['Great Expectations','schema','validation','missing values','type check'] },
  { id:'ml-pipelines', title:'ML Pipelines', domain:'ml', col:'mlops', cat:'Pipeline & Automation', kw:['DAG','pipeline','Kubeflow','Airflow','Vertex'] },
  { id:'feature-stores', title:'Feature Stores', domain:'ml', col:'mlops', cat:'Pipeline & Automation', kw:['Feast','Tecton','feature engineering','online store','offline store'] },
  { id:'experiment-tracking', title:'Experiment Tracking', domain:'ml', col:'mlops', cat:'Pipeline & Automation', kw:['MLflow','Weights & Biases','Neptune','experiment','run'] },
  { id:'ci-cd-ml', title:'CI/CD for ML', domain:'ml', col:'mlops', cat:'Pipeline & Automation', kw:['continuous integration','continuous deployment','GitHub Actions','testing','model validation'] },
  { id:'orchestration', title:'Orchestration & Scheduling', domain:'ml', col:'mlops', cat:'Pipeline & Automation', kw:['Airflow','Prefect','Dagster','cron','scheduler'] },
  { id:'model-compression', title:'Model Compression', domain:'ml', col:'mlops', cat:'Scale & Optimize', kw:['pruning','distillation','knowledge distillation','teacher-student','sparse'] },
  { id:'quantization', title:'Quantization', domain:'ml', col:'mlops', cat:'Scale & Optimize', kw:['INT8','FP16','mixed precision','post-training quantization','quantization-aware training'] },
  { id:'caching-layers', title:'Caching & Prediction Stores', domain:'ml', col:'mlops', cat:'Scale & Optimize', kw:['Redis','cache','prediction store','precompute','lookup'] },
  { id:'auto-scaling', title:'Auto-Scaling Endpoints', domain:'ml', col:'mlops', cat:'Scale & Optimize', kw:['horizontal scaling','Kubernetes HPA','scale-to-zero','cold start','replica'] },
  { id:'cost-governance', title:'Cost Governance', domain:'ml', col:'mlops', cat:'Scale & Optimize', kw:['cloud cost','GPU cost','spot instances','reserved','budget'] },
  { id:'model-registry', title:'Model Registry & Versioning', domain:'ml', col:'mlops', cat:'Governance & Trust', kw:['MLflow registry','model version','staging','production','archive'] },
  { id:'lineage-tracking', title:'Lineage Tracking', domain:'ml', col:'mlops', cat:'Governance & Trust', kw:['data lineage','model lineage','provenance','upstream','downstream'] },
  { id:'fairness-audits', title:'Fairness Audits', domain:'ml', col:'mlops', cat:'Governance & Trust', kw:['bias','fairness','disparate impact','equalized odds','demographic parity'] },
  { id:'reproducibility', title:'Reproducibility', domain:'ml', col:'mlops', cat:'Governance & Trust', kw:['seed','deterministic','environment','DVC','version'] },
  { id:'incident-response', title:'Incident Response for ML', domain:'ml', col:'mlops', cat:'Governance & Trust', kw:['rollback','postmortem','runbook','degradation','fallback'] },

  // ── timeseries (25) ──────────────────────────────
  { id:'stationarity', title:'Stationarity', domain:'ml', col:'timeseries', cat:'Foundations', kw:['mean','variance','ADF test','KPSS','unit root'] },
  { id:'autocorrelation', title:'Autocorrelation (ACF/PACF)', domain:'ml', col:'timeseries', cat:'Foundations', kw:['ACF','PACF','lag','correlogram','serial correlation'] },
  { id:'decomposition', title:'Decomposition', domain:'ml', col:'timeseries', cat:'Foundations', kw:['trend','seasonality','residual','additive','multiplicative'] },
  { id:'differencing', title:'Differencing', domain:'ml', col:'timeseries', cat:'Foundations', kw:['first difference','second difference','seasonal differencing','integration','d parameter'] },
  { id:'resampling', title:'Resampling & Frequency', domain:'ml', col:'timeseries', cat:'Foundations', kw:['downsampling','upsampling','interpolation','frequency conversion','resample'] },
  { id:'ar-models', title:'AR Models', domain:'ml', col:'timeseries', cat:'Classical Models', kw:['autoregressive','AR(p)','lag coefficients','Yule-Walker','past values'] },
  { id:'ma-models', title:'MA Models', domain:'ml', col:'timeseries', cat:'Classical Models', kw:['moving average','MA(q)','error terms','white noise','shock'] },
  { id:'arima', title:'ARIMA', domain:'ml', col:'timeseries', cat:'Classical Models', kw:['ARIMA','p d q','Box-Jenkins','AIC','BIC'] },
  { id:'sarima', title:'SARIMA', domain:'ml', col:'timeseries', cat:'Classical Models', kw:['seasonal ARIMA','P D Q m','seasonal order','monthly','weekly'] },
  { id:'exponential-smoothing', title:'Exponential Smoothing', domain:'ml', col:'timeseries', cat:'Classical Models', kw:['ETS','Holt','Holt-Winters','alpha','beta'] },
  { id:'prophet', title:'Prophet', domain:'ml', col:'timeseries', cat:'Advanced Models', kw:['Facebook Prophet','additive model','holidays','changepoints','yearly'] },
  { id:'state-space', title:'State-Space Models', domain:'ml', col:'timeseries', cat:'Advanced Models', kw:['Kalman filter','hidden state','observation equation','state equation','innovation'] },
  { id:'garch', title:'GARCH', domain:'ml', col:'timeseries', cat:'Advanced Models', kw:['volatility clustering','ARCH','GARCH(1,1)','conditional variance','heteroscedasticity'] },
  { id:'var-models', title:'VAR Models', domain:'ml', col:'timeseries', cat:'Advanced Models', kw:['vector autoregression','multivariate','Granger causality','impulse response','cointegration'] },
  { id:'changepoint-detection', title:'Changepoint Detection', domain:'ml', col:'timeseries', cat:'Advanced Models', kw:['structural break','regime change','PELT','BOCPD','Bayesian online'] },
  { id:'rnn-for-ts', title:'RNNs for Time Series', domain:'ml', col:'timeseries', cat:'Deep Learning', kw:['recurrent neural network','sequence','hidden state','backpropagation through time','BPTT'] },
  { id:'lstm-for-ts', title:'LSTM & GRU', domain:'ml', col:'timeseries', cat:'Deep Learning', kw:['long short-term memory','gated recurrent unit','forget gate','input gate','output gate'] },
  { id:'temporal-cnn', title:'Temporal CNN (TCN)', domain:'ml', col:'timeseries', cat:'Deep Learning', kw:['temporal convolutional network','dilated convolution','causal convolution','WaveNet','receptive field'] },
  { id:'transformers-for-ts', title:'Transformers for Time Series', domain:'ml', col:'timeseries', cat:'Deep Learning', kw:['attention','Informer','Autoformer','PatchTST','time series transformer'] },
  { id:'nbeats', title:'N-BEATS & N-HiTS', domain:'ml', col:'timeseries', cat:'Deep Learning', kw:['neural basis expansion','backward forecast','forward forecast','interpretable','generic'] },
  { id:'feature-engineering', title:'Feature Engineering', domain:'ml', col:'timeseries', cat:'Practice & Tooling', kw:['lag features','rolling mean','rolling std','calendar features','Fourier features'] },
  { id:'cross-validation-ts', title:'Cross-Validation for TS', domain:'ml', col:'timeseries', cat:'Practice & Tooling', kw:['expanding window','sliding window','walk-forward','temporal split','no shuffle'] },
  { id:'backtesting-forecasts', title:'Backtesting Forecasts', domain:'ml', col:'timeseries', cat:'Practice & Tooling', kw:['MAE','RMSE','MAPE','SMAPE','forecast horizon'] },
  { id:'anomaly-detection', title:'Anomaly Detection', domain:'ml', col:'timeseries', cat:'Practice & Tooling', kw:['outlier','spike','dip','z-score','isolation forest'] },
  { id:'forecast-ensembles', title:'Forecast Ensembles', domain:'ml', col:'timeseries', cat:'Practice & Tooling', kw:['ensemble','stacking','weighted average','model combination','diverse'] },

  // ── charts (25) ──────────────────────────────
  { id:'head-and-shoulders', title:'Head & Shoulders', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','top','neckline','left shoulder','right shoulder'] },
  { id:'inverse-head-and-shoulders', title:'Inverse Head & Shoulders', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','bottom','neckline','bullish','breakout'] },
  { id:'double-top', title:'Double Top', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','M pattern','resistance','two peaks','bearish'] },
  { id:'double-bottom', title:'Double Bottom', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['reversal','W pattern','support','two troughs','bullish'] },
  { id:'rounding-bottom', title:'Rounding Bottom', domain:'markets', col:'charts', cat:'Reversal Patterns', kw:['saucer','gradual reversal','accumulation','long-term','bullish'] },
  { id:'bull-flag', title:'Bull Flag', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flag','pole','bullish','consolidation'] },
  { id:'bear-flag', title:'Bear Flag', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flag','pole','bearish','consolidation'] },
  { id:'pennant', title:'Pennant', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','triangle','converging','small','brief'] },
  { id:'ascending-triangle', title:'Ascending Triangle', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flat top','rising lows','bullish','resistance'] },
  { id:'descending-triangle', title:'Descending Triangle', domain:'markets', col:'charts', cat:'Continuation Patterns', kw:['continuation','flat bottom','falling highs','bearish','support'] },
  { id:'symmetric-triangle', title:'Symmetric Triangle', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['bilateral','converging','neutral','breakout either way','indecision'] },
  { id:'rising-wedge', title:'Rising Wedge', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['bearish','converging up','weakening momentum','breakdown','exhaustion'] },
  { id:'falling-wedge', title:'Falling Wedge', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['bullish','converging down','weakening selling','breakout','exhaustion'] },
  { id:'broadening-formation', title:'Broadening Formation', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['megaphone','expanding range','volatility','diverging trendlines','instability'] },
  { id:'rectangle', title:'Rectangle', domain:'markets', col:'charts', cat:'Bilateral & Wedge', kw:['range','consolidation','horizontal','support','resistance'] },
  { id:'doji', title:'Doji', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['indecision','equal open close','cross','neutral','reversal signal'] },
  { id:'hammer', title:'Hammer', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','long lower shadow','bullish','support','rejection'] },
  { id:'engulfing', title:'Engulfing', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','two candle','bullish engulfing','bearish engulfing','body covers'] },
  { id:'morning-star', title:'Morning Star', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','three candle','bullish','bottom','gap down'] },
  { id:'evening-star', title:'Evening Star', domain:'markets', col:'charts', cat:'Candlestick Patterns', kw:['reversal','three candle','bearish','top','gap up'] },
  { id:'support-resistance', title:'Support & Resistance', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['levels','horizontal','price memory','floor','ceiling'] },
  { id:'trendlines', title:'Trendlines', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['diagonal','connecting lows','connecting highs','slope','trend direction'] },
  { id:'channels', title:'Channels', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['parallel trendlines','range','ascending channel','descending channel','trade within'] },
  { id:'gaps', title:'Gaps', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['breakaway','runaway','exhaustion','common','opening gap'] },
  { id:'cup-and-handle', title:'Cup & Handle', domain:'markets', col:'charts', cat:'Structural Analysis', kw:['continuation','rounded bottom','handle','breakout','consolidation'] },

  // ── indicators (25) ──────────────────────────────
  { id:'sma', title:'Simple Moving Average', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['average','mean','smoothing','trend','crossover'] },
  { id:'ema', title:'Exponential Moving Average', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['weighted','recent','responsive','smoothing factor','multiplier'] },
  { id:'wma', title:'Weighted Moving Average', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['linear weight','recent bias','triangle number','smooth','less lag'] },
  { id:'dema', title:'Double Exponential MA', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['Patrick Mulloy','reduced lag','double smoothing','fast','trend following'] },
  { id:'vwap', title:'VWAP', domain:'markets', col:'indicators', cat:'Moving Averages', kw:['volume weighted','institutional','benchmark','intraday','cumulative'] },
  { id:'rsi', title:'Relative Strength Index', domain:'markets', col:'indicators', cat:'Oscillators', kw:['Wilder','overbought','oversold','70','30'] },
  { id:'stochastic', title:'Stochastic Oscillator', domain:'markets', col:'indicators', cat:'Oscillators', kw:['George Lane','%K','%D','overbought','oversold'] },
  { id:'cci', title:'Commodity Channel Index', domain:'markets', col:'indicators', cat:'Oscillators', kw:['Donald Lambert','typical price','mean deviation','+100','-100'] },
  { id:'williams-r', title:'Williams %R', domain:'markets', col:'indicators', cat:'Oscillators', kw:['Larry Williams','overbought','oversold','-20','-80'] },
  { id:'roc', title:'Rate of Change', domain:'markets', col:'indicators', cat:'Oscillators', kw:['momentum','percentage change','zero line','speed','acceleration'] },
  { id:'macd', title:'MACD', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Gerald Appel','12','26','9','signal line'] },
  { id:'adx', title:'Average Directional Index', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Wilder','trend strength','DI+','DI−','directional movement'] },
  { id:'parabolic-sar', title:'Parabolic SAR', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Wilder','stop and reverse','trailing stop','dots','acceleration factor'] },
  { id:'ichimoku', title:'Ichimoku Cloud', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Goichi Hosoda','tenkan','kijun','senkou','chikou'] },
  { id:'aroon', title:'Aroon', domain:'markets', col:'indicators', cat:'Trend & Momentum', kw:['Tushar Chande','Aroon Up','Aroon Down','25-period','new high'] },
  { id:'bollinger-bands', title:'Bollinger Bands', domain:'markets', col:'indicators', cat:'Volatility', kw:['John Bollinger','standard deviation','20-period','2 sigma','squeeze'] },
  { id:'atr', title:'Average True Range', domain:'markets', col:'indicators', cat:'Volatility', kw:['Wilder','true range','volatility','position sizing','stop loss'] },
  { id:'keltner-channels', title:'Keltner Channels', domain:'markets', col:'indicators', cat:'Volatility', kw:['Chester Keltner','ATR','EMA','channel','trend'] },
  { id:'donchian-channels', title:'Donchian Channels', domain:'markets', col:'indicators', cat:'Volatility', kw:['Richard Donchian','highest high','lowest low','20-period','turtle traders'] },
  { id:'standard-deviation', title:'Standard Deviation', domain:'markets', col:'indicators', cat:'Volatility', kw:['sigma','variance','dispersion','normal distribution','volatility measure'] },
  { id:'obv', title:'On-Balance Volume', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['Joe Granville','cumulative volume','confirmation','divergence','breakout'] },
  { id:'accumulation-distribution', title:'Accumulation/Distribution', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['Marc Chaikin','money flow multiplier','CLV','cumulative','divergence'] },
  { id:'mfi', title:'Money Flow Index', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['volume RSI','typical price','money flow','overbought','oversold'] },
  { id:'chaikin-oscillator', title:'Chaikin Oscillator', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['Marc Chaikin','A/D line','3-day EMA','10-day EMA','MACD of A/D'] },
  { id:'vwap-bands', title:'VWAP Bands', domain:'markets', col:'indicators', cat:'Volume Indicators', kw:['VWAP','standard deviation bands','1σ','2σ','intraday'] },

  // ── psychology (25) ──────────────────────────────
  { id:'confirmation-bias', title:'Confirmation Bias', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['selective','seeking evidence','ignoring contrary','belief','filter'] },
  { id:'anchoring', title:'Anchoring', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['reference point','first number','price anchor','adjustment','insufficient'] },
  { id:'recency-bias', title:'Recency Bias', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['recent events','extrapolation','short memory','trend chasing','last quarter'] },
  { id:'availability-heuristic', title:'Availability Heuristic', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['vivid memories','media','dramatic events','probability','overweight'] },
  { id:'hindsight-bias', title:'Hindsight Bias', domain:'markets', col:'psychology', cat:'Cognitive Biases', kw:['knew it all along','predictable','retroactive','overestimate','narrative fallacy'] },
  { id:'fear-and-greed', title:'Fear & Greed', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['emotion cycle','index','extreme fear','extreme greed','Buffett'] },
  { id:'loss-aversion', title:'Loss Aversion', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['Kahneman','Tversky','prospect theory','2x pain','losses loom larger'] },
  { id:'regret-aversion', title:'Regret Aversion', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['anticipated regret','inaction','omission','commission','paralysis'] },
  { id:'overconfidence', title:'Overconfidence', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['illusion of control','above average','excessive trading','Barber','Odean'] },
  { id:'disposition-effect', title:'Disposition Effect', domain:'markets', col:'psychology', cat:'Emotional Drivers', kw:['sell winners','hold losers','Shefrin','Statman','tax inefficient'] },
  { id:'herd-behavior', title:'Herd Behavior', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['crowd','following','momentum','bubble','crash'] },
  { id:'fomo', title:'FOMO', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['fear of missing out','buying tops','late entry','anxiety','social media'] },
  { id:'social-proof', title:'Social Proof', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['Cialdini','mimicry','influencer','expert opinion','crowd wisdom'] },
  { id:'contrarian-thinking', title:'Contrarian Thinking', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['opposite','against the crowd','buy fear','sell greed','value investing'] },
  { id:'information-cascades', title:'Information Cascades', domain:'markets', col:'psychology', cat:'Herd & Social', kw:['sequential decisions','ignore private signal','rational herding','domino','Banerjee'] },
  { id:'sunk-cost-fallacy', title:'Sunk Cost Fallacy', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['throwing good money after bad','past investment','irreversible','doubling down','committed'] },
  { id:'gambler-fallacy', title:'Gambler\'s Fallacy', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['hot hand','due','independent events','pattern','randomness'] },
  { id:'framing-effect', title:'Framing Effect', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['presentation','wording','gain frame','loss frame','Tversky'] },
  { id:'mental-accounting', title:'Mental Accounting', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['Thaler','separate buckets','house money','found money','fungibility'] },
  { id:'status-quo-bias', title:'Status Quo Bias', domain:'markets', col:'psychology', cat:'Decision Traps', kw:['inertia','default option','endowment','change aversion','rebalancing'] },
  { id:'market-sentiment-cycle', title:'Market Sentiment Cycle', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['disbelief','hope','optimism','euphoria','anxiety'] },
  { id:'accumulation-distribution', title:'Accumulation & Distribution', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['Wyckoff','smart money','phases','markup','markdown'] },
  { id:'euphoria-panic', title:'Euphoria & Panic', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['mania','bubble','crash','capitulation','extreme emotion'] },
  { id:'smart-money-dumb-money', title:'Smart Money vs. Dumb Money', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['institutional','retail','COT report','insider buying','late buyers'] },
  { id:'mean-reversion-psychology', title:'Mean Reversion Psychology', domain:'markets', col:'psychology', cat:'Market Cycles', kw:['regression to mean','overshoot','undershoot','extremes revert','patience'] },

  // ── risk (25) ──────────────────────────────
  { id:'value-at-risk', title:'Value at Risk (VaR)', domain:'markets', col:'risk', cat:'Risk Measures', kw:['var','value at risk','confidence','loss','parametric'] },
  { id:'expected-shortfall', title:'Expected Shortfall (CVaR)', domain:'markets', col:'risk', cat:'Risk Measures', kw:['cvar','expected shortfall','conditional','tail','average'] },
  { id:'volatility-modeling', title:'Volatility Modeling', domain:'markets', col:'risk', cat:'Risk Measures', kw:['garch','ewma','realized','implied','stochastic'] },
  { id:'correlation-risk', title:'Correlation Risk', domain:'markets', col:'risk', cat:'Risk Measures', kw:['correlation','covariance','regime','breakdown','contagion'] },
  { id:'tail-risk', title:'Tail Risk', domain:'markets', col:'risk', cat:'Risk Measures', kw:['tail','kurtosis','fat tails','black swan','extreme'] },
  { id:'mean-variance', title:'Mean-Variance Optimization', domain:'markets', col:'risk', cat:'Portfolio Construction', kw:['markowitz','efficient frontier','optimization','sharpe','quadratic'] },
  { id:'risk-parity', title:'Risk Parity', domain:'markets', col:'risk', cat:'Portfolio Construction', kw:['risk parity','equal risk','contribution','all weather','bridgewater'] },
  { id:'factor-models', title:'Factor Models', domain:'markets', col:'risk', cat:'Portfolio Construction', kw:['factor','fama french','capm','beta','momentum'] },
  { id:'rebalancing', title:'Rebalancing Strategies', domain:'markets', col:'risk', cat:'Portfolio Construction', kw:['rebalance','threshold','calendar','drift','transaction cost'] },
  { id:'diversification', title:'Diversification', domain:'markets', col:'risk', cat:'Portfolio Construction', kw:['diversification','asset class','cross-asset','regime','correlation'] },
  { id:'kelly-criterion', title:'Kelly Criterion', domain:'markets', col:'risk', cat:'Position Sizing', kw:['kelly','optimal','fraction','edge','odds'] },
  { id:'fixed-fractional', title:'Fixed Fractional Sizing', domain:'markets', col:'risk', cat:'Position Sizing', kw:['fixed fractional','percent risk','constant','position','lot size'] },
  { id:'volatility-sizing', title:'Volatility-Based Sizing', domain:'markets', col:'risk', cat:'Position Sizing', kw:['volatility','atr','normalize','size','turtle'] },
  { id:'pyramiding', title:'Pyramiding', domain:'markets', col:'risk', cat:'Position Sizing', kw:['pyramid','add','scale in','winner','trend'] },
  { id:'max-position', title:'Maximum Position Limits', domain:'markets', col:'risk', cat:'Position Sizing', kw:['max position','concentration','limit','exposure','single name'] },
  { id:'options-hedging', title:'Options Hedging', domain:'markets', col:'risk', cat:'Hedging & Protection', kw:['options','put','collar','protective','delta'] },
  { id:'stop-losses', title:'Stop-Loss Strategies', domain:'markets', col:'risk', cat:'Hedging & Protection', kw:['stop loss','trailing','hard stop','percentage','atr stop'] },
  { id:'pairs-trading', title:'Pairs Trading', domain:'markets', col:'risk', cat:'Hedging & Protection', kw:['pairs','spread','cointegration','mean reversion','market neutral'] },
  { id:'portfolio-insurance', title:'Portfolio Insurance', domain:'markets', col:'risk', cat:'Hedging & Protection', kw:['cppi','obpi','insurance','floor','cushion'] },
  { id:'currency-hedging', title:'Currency Hedging', domain:'markets', col:'risk', cat:'Hedging & Protection', kw:['currency','fx','forward','cross-currency','unhedged'] },
  { id:'return-attribution', title:'Return Attribution', domain:'markets', col:'risk', cat:'Performance & Attribution', kw:['attribution','brinson','allocation','selection','interaction'] },
  { id:'benchmark-tracking', title:'Benchmark Tracking', domain:'markets', col:'risk', cat:'Performance & Attribution', kw:['tracking error','benchmark','index','passive','active share'] },
  { id:'alpha-generation', title:'Alpha Generation', domain:'markets', col:'risk', cat:'Performance & Attribution', kw:['alpha','excess return','skill','information ratio','active management'] },
  { id:'risk-adjusted-perf', title:'Risk-Adjusted Performance', domain:'markets', col:'risk', cat:'Performance & Attribution', kw:['sharpe','sortino','calmar','treynor','information ratio'] },
  { id:'drawdown-analysis', title:'Drawdown Analysis', domain:'markets', col:'risk', cat:'Performance & Attribution', kw:['drawdown','maximum drawdown','recovery','underwater','peak to trough'] },
];

// Unique categories per domain for wave challenges
const CATEGORIES = {};
GAME_TOPICS.forEach(t => {
  if (!CATEGORIES[t.domain]) CATEGORIES[t.domain] = new Set();
  CATEGORIES[t.domain].add(t.cat);
});
Object.keys(CATEGORIES).forEach(d => CATEGORIES[d] = [...CATEGORIES[d]]);

// Cross-domain keywords (appear in 2+ domains) for hard waves
const CROSS_KEYWORDS = (function() {
  const kwMap = {};
  GAME_TOPICS.forEach(t => {
    t.kw.forEach(k => {
      const kl = k.toLowerCase();
      if (!kwMap[kl]) kwMap[kl] = new Set();
      kwMap[kl].add(t.domain);
    });
  });
  return Object.entries(kwMap)
    .filter(([, domains]) => domains.size >= 2)
    .map(([kw, domains]) => ({ kw, domains: [...domains] }));
})();
