/* ── Pattern trails ──
   A trail follows one pattern across collections — the bell curve from the
   CLT to Bollinger Bands to tail risk — as a numbered route with a note on
   why each stop belongs. The site's argument is that patterns recur across
   fields; until now a visitor had to discover that alone.

   Source: trails/trails.json (hand-edited). This writes, from it and
   connections.json:
     /trails/index.html          all trails
     /trails/<id>/index.html     one trail: intro, stops, outro
     index.html                  the homepage's "Pattern trails" block
     sitemap.xml                 the trail pages
     assets/og/trails/<id>.jpg   share cards (with --cards, or when missing;
                                 needs Chrome, via scripts/chrome.mjs)

   Stops link into the collection readers with ?trail=<id>, where
   js/trails.js shows the stop's note and the way on.

   Usage:  node scripts/build-trails.mjs [--cards]
           node scripts/build-trails.mjs --check   (drift only; exits 1) */
import { readFileSync, existsSync } from 'node:fs';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://patterniseverything.com';
const args = process.argv.slice(2);
const CHECK = args.includes('--check');
const CARDS = args.includes('--cards');

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
  .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const hash8 = file => createHash('sha256').update(readFileSync(file)).digest('hex').slice(0, 8);
const lf = s => s.replace(/\r\n/g, '\n');

const { trails } = JSON.parse(readFileSync(join(ROOT, 'trails', 'trails.json'), 'utf8'));
const { topics } = JSON.parse(readFileSync(join(ROOT, 'connections.json'), 'utf8'));

/* Every stop must be a real topic; a typo would ship a dead link. */
const problems = [];
const ids = new Set();
for (const t of trails) {
  if (!/^[a-z0-9-]+$/.test(t.id) || ids.has(t.id)) problems.push(`trail id "${t.id}" is missing, malformed or repeated`);
  ids.add(t.id);
  if (!t.stops || t.stops.length < 3) problems.push(`${t.id}: a trail needs at least 3 stops`);
  for (const s of t.stops || []) if (!topics[s.key]) problems.push(`${t.id}: no topic ${s.key}`);
}
if (problems.length) { console.error(problems.map(p => '  ✗ ' + p).join('\n')); process.exit(1); }

/* "/stats/#clt-sampling" → the reader URL that opens it on this trail. */
const stopUrl = (trail, key) => { const [p, id] = key.split('#'); return `${p}?trail=${trail.id}#${id}`; };
const thumbOf = key => {
  const t = topics[key];
  return t.i ? `/assets/thumbs/${key.slice(1).replace('/#', '/')}.webp?v=${t.i}` : null;
};
const collectionsOf = trail => [...new Set(trail.stops.map(s => topics[s.key].c))];
const cardPath = trail => join(ROOT, 'assets', 'og', 'trails', `${trail.id}.jpg`);
const ogImageOf = trail => existsSync(cardPath(trail))
  ? `${SITE}/assets/og/trails/${trail.id}.jpg?v=${hash8(cardPath(trail))}`
  : `${SITE}/assets/og/og-start.png`;

/* A trail as a card: the homepage block and the /trails/ index share it. */
function trailCard(trail) {
  const strip = trail.stops.slice(0, 4).map(s => thumbOf(s.key)).filter(Boolean)
    .map(src => `<img src="${esc(src)}" alt="" loading="lazy" decoding="async">`).join('');
  return `<a class="trail-card" href="/trails/${trail.id}/" data-trail="${trail.id}">
      <div class="trail-card-strip" aria-hidden="true">${strip}</div>
      <div class="trail-card-body">
        <div class="trail-card-kicker">${trail.stops.length} stops · ${esc(collectionsOf(trail).join(' · '))}</div>
        <div class="trail-card-title">${esc(trail.title)}</div>
        <p class="trail-card-intro">${esc(trail.intro)}</p>
        <div class="trail-card-foot"><span class="trail-card-progress" data-trail-progress="${trail.id}"></span><span class="trail-card-go">Follow the trail →</span></div>
      </div>
    </a>`;
}

function shell({ title, desc, canonical, ogImage, h1, body, extraHead = '' }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}">
  <link rel="canonical" href="${canonical}">
  <meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">
  <!-- Generated by scripts/build-trails.mjs from trails/trails.json — do not edit by hand. -->
  <meta name="theme-color" content="#c84b2f" media="(prefers-color-scheme: light)">
  <meta name="theme-color" content="#141210" media="(prefers-color-scheme: dark)">
  <meta name="color-scheme" content="light dark">
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png">
  <meta property="og:type" content="article">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(desc)}">
  <meta property="og:url" content="${canonical}">
  <meta property="og:site_name" content="Pattern is Everything">
  <meta property="og:image" content="${ogImage}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${esc(title)}">
  <meta name="twitter:description" content="${esc(desc)}">
  <meta name="twitter:image" content="${ogImage}">
${extraHead}  <link rel="stylesheet" href="/css/fonts.css?v=1">
  <link rel="stylesheet" href="/css/main.css?v=31">
  <link rel="preconnect" href="https://patterniseverything.goatcounter.com">
  <script data-goatcounter="https://patterniseverything.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
</head>
<body>
<script>(function(){var s=localStorage.getItem('theme');if(s)document.documentElement.setAttribute('data-theme',s);else if(window.matchMedia('(prefers-color-scheme:dark)').matches)document.documentElement.setAttribute('data-theme','dark');})()</script>

<div class="portal-header" role="banner">
  <a class="logo-ring" href="/" title="Back to Pattern is Everything"></a>
  <h1 style="font-family:var(--serif);font-size:20px;font-weight:700;letter-spacing:-.01em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0;">
    ${h1}
  </h1>
  <nav class="portal-nav" aria-label="Primary">
    <a href="/ml/">ML</a>
    <a href="/stats/">Stats</a>
    <a href="/markets/">Markets</a>
    <a href="/essays/">Essays</a>
    <a href="/cases/">Cases</a>
    <a href="/sandbox/">Sandbox</a>
    <a href="/lab/">Lab</a>
    <a href="/start/">Start here</a>
  </nav>
  <div style="margin-left:auto;display:flex;gap:8px;align-items:center;">
    <button class="theme-toggle" onclick="toggleTheme()" title="Toggle dark mode">◐</button>
    <a class="back-link" href="/trails/">← All trails</a>
  </div>
</div>

<main class="trail-page">
${body}
</main>

<script>
function toggleTheme() {
  var d = document.documentElement;
  d.setAttribute('data-theme', d.getAttribute('data-theme') === 'dark' ? 'light' : 'dark');
  localStorage.setItem('theme', d.getAttribute('data-theme'));
}
</script>
<script src="/js/track.js?v=1" defer></script>
<script src="/js/progress.js?v=1" defer></script>
<script src="/js/connections.js?v=3" defer></script>
<script src="/js/trails.js?v=1" defer></script>
<script src="/js/ui-enhance.js?v=30" defer></script>
</body>
</html>
`;
}

/* Hero blocks are divs: main.css styles every <header> as the fixed top bar. */
function trailPage(trail) {
  const canonical = `${SITE}/trails/${trail.id}/`;
  const stops = trail.stops.map((s, i) => {
    const t = topics[s.key];
    const thumb = thumbOf(s.key);
    return `  <li class="trail-stop" data-key="${esc(s.key)}">
    <a class="trail-stop-link" href="${esc(stopUrl(trail, s.key))}" data-trail-nav>
      <span class="trail-stop-num" aria-hidden="true">${i + 1}</span>
      <span class="trail-stop-text">
        <span class="trail-stop-col">${esc(t.c)}</span>
        <span class="trail-stop-title">${esc(t.t)}</span>
        <span class="trail-stop-note">${esc(s.note)}</span>
      </span>
      ${thumb ? `<span class="trail-stop-thumb"><img src="${esc(thumb)}" alt="" loading="lazy" decoding="async"></span>` : ''}
    </a>
  </li>`;
  }).join('\n');
  const others = trails.filter(t => t.id !== trail.id).map(trailCard).join('\n    ');
  const ld = JSON.stringify({
    '@context': 'https://schema.org', '@type': 'ItemList', name: trail.title, description: trail.intro, url: canonical,
    numberOfItems: trail.stops.length,
    itemListElement: trail.stops.map((s, i) => ({ '@type': 'ListItem', position: i + 1, name: topics[s.key].t,
      url: `${SITE}/${s.key.slice(1).replace('/#', '/')}/` })),
  }, null, 2).replace(/\n/g, '\n  ');
  const body = `<div class="trail-hero">
  <div class="trail-kicker">Pattern trail · ${trail.stops.length} stops · ${esc(collectionsOf(trail).join(' · '))}</div>
  <h2>${esc(trail.title)}</h2>
  <p class="trail-intro">${esc(trail.intro)}</p>
  <div class="trail-actions">
    <a class="trail-start" href="${esc(stopUrl(trail, trail.stops[0].key))}" data-trail-nav data-trail-start="${trail.id}">Start the trail →</a>
    <span class="trail-progress" data-trail-progress="${trail.id}"></span>
  </div>
</div>

<ol class="trail-stops" data-trail="${trail.id}">
${stops}
</ol>

<section class="trail-outro">
  <div class="trail-kicker">The pattern</div>
  <p>${esc(trail.outro)}</p>
</section>

<section class="trail-more">
  <div class="trail-kicker">More trails</div>
  <div class="trail-grid">
    ${others}
  </div>
</section>`;
  return shell({
    title: `${trail.title} — Pattern trail`, desc: trail.intro, canonical, ogImage: ogImageOf(trail),
    h1: 'Pattern <em style="font-style:italic;color:var(--accent)">trails</em>', body,
    extraHead: `  <script type="application/ld+json">\n  ${ld}\n  </script>\n`,
  });
}

function indexPage() {
  const body = `<div class="trail-hero">
  <div class="trail-kicker">Pattern trails</div>
  <h2>Follow one pattern <em>across fields</em></h2>
  <p class="trail-intro">Each trail takes one idea — the bell curve, regression to the mean, feedback — through statistics, machine learning and markets, a few stops at a time, with a note at each on why it belongs.</p>
</div>

<div class="trail-grid trail-grid-index">
    ${trails.map(trailCard).join('\n    ')}
</div>`;
  return shell({
    title: 'Pattern trails — Pattern is Everything',
    desc: 'Guided routes that follow one pattern across statistics, machine learning and markets.',
    canonical: `${SITE}/trails/`, ogImage: `${SITE}/assets/og/og-start.png`,
    h1: 'Pattern <em style="font-style:italic;color:var(--accent)">trails</em>', body,
  });
}

const H_START = '<!-- trails:start -->', H_END = '<!-- trails:end -->';
function homeBlock() {
  return `${H_START}
<!-- Generated by scripts/build-trails.mjs from trails/trails.json. -->
<div class="trails-home">
  <div class="section-head">
    <div class="section-kicker">Pattern trails</div>
    <h2>Follow one pattern <em>across fields</em></h2>
  </div>
  <div class="trail-grid">
    ${trails.slice(0, 3).map(trailCard).join('\n    ')}
  </div>
  <a class="trails-all" href="/trails/">All ${trails.length} trails →</a>
</div>
${H_END}`;
}

const S_START = '  <!-- trails:start -->', S_END = '  <!-- trails:end -->';
function sitemapBlock(xml) {
  // Keep each URL's lastmod unless its page changed; the caller decides.
  const urls = [`${SITE}/trails/`, ...trails.map(t => `${SITE}/trails/${t.id}/`)];
  return [S_START, ...urls.map(u =>
    `  <url>\n    <loc>${u}</loc>\n    <priority>0.7</priority>\n    <lastmod>${new Date().toISOString().slice(0, 10)}</lastmod>\n  </url>`), S_END].join('\n');
}

/* Write `file` if its content (ignoring line endings) changed. In --check
   mode, report instead. Keeps the file's own line endings. */
let stale = 0, written = 0;
async function sync(file, next, label = file, compare = s => s) {
  const abs = join(ROOT, file);
  const cur = existsSync(abs) ? await readFile(abs, 'utf8') : null;
  if (cur !== null && compare(lf(cur)) === compare(lf(next))) return;
  if (CHECK) { stale++; console.log(`  stale: ${label}`); return; }
  const eol = cur && cur.includes('\r\n') ? '\r\n' : '\n';
  await mkdir(dirname(abs), { recursive: true });
  await writeFile(abs, lf(next).replace(/\n/g, eol));
  written++;
}

/* A synced folder (OneDrive) can briefly lock a file it is uploading, and
   rewriting it then fails with EBUSY/EPERM/UNKNOWN. A short retry rides that out. */
async function put(file, data) {
  await mkdir(dirname(file), { recursive: true });
  for (let attempt = 1; ; attempt++) {
    try { return await writeFile(file, data); }
    catch (e) {
      if (attempt >= 6 || !['EBUSY', 'EPERM', 'EACCES', 'UNKNOWN'].includes(e.code)) throw e;
      await new Promise(r => setTimeout(r, 500 * attempt));
    }
  }
}

async function buildCards(only) {
  const { serve, launch, connect } = await import('./chrome.mjs');
  const server = await serve(ROOT);
  const base = `http://127.0.0.1:${server.address().port}`;
  const browser = await launch();
  try {
    const card = await connect(browser.port);
    await card.send('Page.enable');
    await card.send('Emulation.setDeviceMetricsOverride', { width: 1200, height: 630, deviceScaleFactor: 1, mobile: false });
    await card.send('Page.bringToFront');
    await card.goto(`${base}/scripts/og-card.html`);
    for (const trail of only) {
      // The stop whose visualization shows the most — the largest thumbnail,
      // since a near-empty picture compresses to almost nothing.
      const thumbFile = trail.stops
        .map(s => join(ROOT, 'assets', 'thumbs', `${s.key.slice(1).replace('/#', '/')}.webp`))
        .filter(f => existsSync(f))
        .sort((a, b) => readFileSync(b).length - readFileSync(a).length)[0];
      const src = thumbFile ? `data:image/webp;base64,${readFileSync(thumbFile).toString('base64')}` : '';
      const f = JSON.stringify({ collection: `Pattern trail · ${trail.stops.length} stops`, title: trail.title,
        pattern: collectionsOf(trail).join(' → '), src });
      await card.evaluate(`(async () => {
        const f = ${f};
        document.querySelector('.col').textContent = 'Pattern is Everything · ' + f.collection;
        document.querySelector('.title').textContent = f.title;
        document.querySelector('.pattern').textContent = f.pattern;
        document.body.classList.toggle('no-viz', !f.src);
        const img = document.querySelector('.viz img');
        img.src = f.src;
        if (f.src) await img.decode();
        document.body.classList.toggle('side', !!f.src && img.naturalWidth / img.naturalHeight < 2.2);
        await document.fonts.ready;
        return true;
      })()`);
      const shot = Buffer.from((await card.send('Page.captureScreenshot', { format: 'jpeg', quality: 86 })).data, 'base64');
      await put(cardPath(trail), shot);
      console.log(`assets/og/trails/${trail.id}.jpg`);
    }
    card.close();
  } finally {
    server.close();
    await browser.close();
  }
}

async function run() {
  if (!CHECK) {
    const need = trails.filter(t => CARDS || !existsSync(cardPath(t)));
    if (need.length) await buildCards(need);
  }
  await sync('trails/index.html', indexPage());
  for (const t of trails) await sync(`trails/${t.id}/index.html`, trailPage(t));

  const home = await readFile(join(ROOT, 'index.html'), 'utf8');
  if (!home.includes(H_START)) throw new Error(`index.html has no ${H_START} marker`);
  await sync('index.html', home.replace(new RegExp(`${H_START}[\\s\\S]*?${H_END}`), homeBlock()), 'index.html trails block');

  const xml = lf(await readFile(join(ROOT, 'sitemap.xml'), 'utf8'));
  const block = sitemapBlock(xml);
  const nextXml = xml.includes(S_START)
    ? xml.replace(new RegExp(`${S_START}[\\s\\S]*?${S_END}`), block)
    : xml.replace('</urlset>', `${block}\n</urlset>`);
  // A date bump alone is not drift.
  await sync('sitemap.xml', nextXml, 'sitemap.xml trails block', s => s.replace(/<lastmod>[^<]*<\/lastmod>/g, ''));

  if (CHECK) {
    if (stale) { console.error(`${stale} trail file(s) out of date — run: node scripts/build-trails.mjs`); process.exit(1); }
    console.log(`trails: ${trails.length} trails, all generated files current`);
  } else {
    console.log(`trails: ${trails.length} trails, ${written} file(s) written`);
  }
}

run().catch(e => { console.error(e); process.exit(1); });
