/* ── connections.json — the pattern-bridge graph ──
   Every topic's pattern bridges link out to topics in other collections, but
   nothing pointed the other way: Support & Resistance had no idea that
   Activation Functions, and others, lead to it. This walks the pre-rendered
   topic pages — they carry exactly the markup readers see, in one format for
   every collection — and records each topic's title, collection and pattern
   line, plus which topics link to it.

   js/connections.js uses it for the "Linked from" list under each topic and
   for the preview card when hovering a bridge. Built by scripts/build.mjs;
   scripts/check.mjs fails when it has drifted from the pages.

   Keys are reader URLs, "/ml-math/#activation", which is what the links in
   topic markup point at. */
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const COLLECTIONS = [
  'stats', 'ml-math', 'llm', 'mlops', 'timeseries', 'essays',
  'markets/charts', 'markets/indicators', 'markets/psychology', 'markets/risk',
];

const decode = s => s.replace(/<[^>]*>/g, '').replace(/&amp;/g, '&').replace(/&lt;/g, '<')
  .replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\s+/g, ' ').trim();

/* A reader URL for an href on the pre-rendered page at /<col>/<id>/, or null
   when it doesn't point at a topic. */
function readerKey(href, pagePath) {
  let u;
  try { u = new URL(href, 'https://x' + pagePath); } catch { return null; }
  if (u.host !== 'x' || !u.hash) return null;
  return u.pathname.replace(/index\.html$/, '') + u.hash;
}

export function buildConnections(root = '.') {
  const topics = {};
  const outgoing = {};
  for (const col of COLLECTIONS) {
    for (const d of readdirSync(join(root, col), { withFileTypes: true })) {
      const file = join(root, col, d.name, 'index.html');
      if (!d.isDirectory() || !existsSync(file)) continue;
      const html = readFileSync(file, 'utf8');
      if (!html.includes('Generated by scripts/prerender.mjs')) continue;
      const key = `/${col}/#${d.name}`;
      const [title, collection] = decode(html.match(/<title>([\s\S]*?)<\/title>/)[1]).split(' — ');
      const pattern = html.match(/<span class="pt-text">([\s\S]*?)<\/span>/);
      topics[key] = { t: title, c: collection || '', p: pattern ? decode(pattern[1]) : '' };
      // Only the topic's own markup: between its opening div and the
      // generated prev/next links, so the header, crumbs and nav don't count.
      const start = html.indexOf('<div class="topic"');
      const end = html.indexOf('<div class="topic-nav">', start);
      const body = html.slice(start, end);
      const out = new Set();
      for (const m of body.matchAll(/<a\b[^>]*?\shref="([^"]+)"/g)) {
        const k = readerKey(m[1], `/${col}/${d.name}/`);
        if (k && k !== key) out.add(k);
      }
      outgoing[key] = out;
    }
  }
  // Keep links that land on a real topic; dead anchors are check.mjs's to report.
  const linkedFrom = {};
  for (const [from, outs] of Object.entries(outgoing)) {
    for (const to of outs) {
      if (!topics[to]) continue;
      (linkedFrom[to] ||= []).push(from);
    }
  }
  const sortedTopics = Object.fromEntries(Object.keys(topics).sort().map(k => [k, topics[k]]));
  const sortedLinks = Object.fromEntries(Object.keys(linkedFrom).sort().map(k => [k, linkedFrom[k].sort()]));
  return { topics: sortedTopics, linkedFrom: sortedLinks };
}
