/* ── Content report ──
   Where the topics stand against the content standard: how much each one
   says, whether its pattern line is an insight or just a formula, and
   whether it links to — and is linked from — the rest of the site. Read from
   the pre-rendered pages and connections.json, so run it after a build.

   Used by scripts/check.mjs (as warnings, never failures — content is fixed
   by writing, not by a script) and by scripts/build.mjs, which writes the
   table to /content/ (not indexed, not linked from the site).

   Usage:  node scripts/content-report.mjs      prints the summary */
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const MIN_WORDS = 150;

const text = s => s.replace(/<script[\s\S]*?<\/script>/g, '').replace(/<style[\s\S]*?<\/style>/g, '')
  .replace(/<[^>]*>/g, ' ').replace(/&[a-z#0-9]+;/g, ' ').replace(/\s+/g, ' ').trim();

/* A pattern line that is a formula rather than an insight: one that opens as
   an equation ("RSI = …", "Middle = SMA(20)…") or carries a summation or a
   root. "Sharp rally + falling channel = continuation" is prose and passes. */
export const looksLikeFormula = p => /Σ|√/.test(p) || /^\S+(\s\S+)?\s*[+\-]?=\s/.test(p);

export function contentInventory(root = ROOT) {
  const c = JSON.parse(readFileSync(join(root, 'connections.json'), 'utf8'));
  const out = {};
  for (const froms of Object.values(c.linkedFrom)) for (const f of froms) out[f] = (out[f] || 0) + 1;
  const rows = [];
  for (const [key, t] of Object.entries(c.topics)) {
    const [p, id] = key.split('#');
    const file = join(root, p, id, 'index.html');
    if (!existsSync(file)) continue;
    const html = readFileSync(file, 'utf8');
    const s = html.search(/<div class="topic[ "]/);
    const conn = html.indexOf('<section class="topic-connections"', s);
    const e = conn !== -1 ? conn : html.indexOf('<div class="topic-nav">', s);
    const body = html.slice(s, e);
    rows.push({
      key, collection: t.c, title: t.t, pattern: t.p,
      words: text(body).split(' ').length,
      out: out[key] || 0,
      in: (c.linkedFrom[key] || []).length,
      code: /<pre|<code/.test(body),
      formulaLine: looksLikeFormula(t.p),
    });
  }
  return rows;
}

export function summarize(rows) {
  const by = {};
  for (const r of rows) (by[r.collection] ||= []).push(r);
  const median = a => { const s = [...a].sort((x, y) => x - y); return s[Math.floor(s.length / 2)]; };
  return Object.entries(by).map(([collection, rs]) => ({
    collection, topics: rs.length,
    medianWords: median(rs.map(r => r.words)),
    short: rs.filter(r => r.words < MIN_WORDS).length,
    noOut: rs.filter(r => !r.out).length,
    noIn: rs.filter(r => !r.in).length,
    formulaLines: rs.filter(r => r.formulaLine).length,
    withCode: rs.filter(r => r.code).length,
  }));
}

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/* The /content/ page: the per-collection summary and every topic that falls
   short, worst first. */
export function reportHtml(rows) {
  const sum = summarize(rows);
  const tot = k => rows.filter(k).length;
  const gaps = rows.filter(r => r.words < MIN_WORDS || !r.out || !r.in || r.formulaLine)
    .sort((a, b) => (b.formulaLine + !b.out + !b.in + (b.words < MIN_WORDS)) - (a.formulaLine + !a.out + !a.in + (a.words < MIN_WORDS)) || a.words - b.words);
  const flag = (on, label) => on ? `<span class="f">${label}</span>` : '';
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="noindex,nofollow">
<title>Content report — Pattern is Everything</title>
<!-- Generated by scripts/build.mjs (scripts/content-report.mjs) — do not edit by hand. -->
<style>
  :root { --bg:#faf8f4; --fg:#1c1a16; --muted:#6f665b; --line:#e6dfd3; --accent:#c84b2f; }
  @media (prefers-color-scheme: dark) { :root { --bg:#141210; --fg:#e9e3d7; --muted:#9a8e80; --line:#2e2a25; --accent:#e0694c; } }
  body { background:var(--bg); color:var(--fg); font:14px/1.5 system-ui, sans-serif; margin:0; padding:24px 16px 64px; }
  main { max-width:1100px; margin:0 auto; }
  h1 { font:700 26px Georgia, serif; margin:0 0 4px; }
  p { color:var(--muted); margin:0 0 20px; }
  .wrap { overflow-x:auto; margin:0 0 32px; }
  table { border-collapse:collapse; width:100%; min-width:640px; }
  th, td { text-align:left; padding:6px 10px; border-bottom:1px solid var(--line); }
  th { font:600 11px ui-monospace, monospace; text-transform:uppercase; letter-spacing:.05em; color:var(--muted); }
  td.n { text-align:right; font-variant-numeric:tabular-nums; font-family:ui-monospace, monospace; }
  .f { display:inline-block; margin:0 4px 2px 0; padding:0 6px; border-radius:4px; font:11px ui-monospace, monospace; color:var(--accent); border:1px solid var(--accent); }
  a { color:inherit; }
</style>
</head>
<body><main>
<h1>Content report</h1>
<p>${rows.length} topics · ${tot(r => !r.in)} with no links in · ${tot(r => !r.out)} with no links out · ${tot(r => r.formulaLine)} formula pattern lines · ${tot(r => r.words < MIN_WORDS)} under ${MIN_WORDS} words. Generated ${new Date().toISOString().slice(0, 10)}.</p>
<div class="wrap"><table>
<thead><tr><th>Collection</th><th>Topics</th><th>Median words</th><th>Under ${MIN_WORDS}</th><th>No links out</th><th>No links in</th><th>Formula line</th><th>With code</th></tr></thead>
<tbody>
${sum.map(s => `<tr><td>${esc(s.collection)}</td><td class="n">${s.topics}</td><td class="n">${s.medianWords}</td><td class="n">${s.short}</td><td class="n">${s.noOut}</td><td class="n">${s.noIn}</td><td class="n">${s.formulaLines}</td><td class="n">${s.withCode}</td></tr>`).join('\n')}
</tbody></table></div>
<div class="wrap"><table>
<thead><tr><th>Topic</th><th>Collection</th><th>Words</th><th>Out</th><th>In</th><th>Gaps</th></tr></thead>
<tbody>
${gaps.map(r => `<tr><td><a href="${esc(r.key)}">${esc(r.title)}</a></td><td>${esc(r.collection)}</td><td class="n">${r.words}</td><td class="n">${r.out}</td><td class="n">${r.in}</td><td>${flag(r.formulaLine, 'formula line')}${flag(!r.out, 'no links out')}${flag(!r.in, 'no links in')}${flag(r.words < MIN_WORDS, 'short')}</td></tr>`).join('\n')}
</tbody></table></div>
</main></body>
</html>
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const rows = contentInventory();
  console.table(summarize(rows));
}
